Repository RasaHQ/rasa, pull requests merged in 2019-05, with the labels that each got.

#3516 fix new persistence of CountVectorsFeaturizer
  rasa/nlu/featurizers/count_vectors_featurizer.py
  tests/nlu/base/test_featurizers.py
Labels: bug

#3517 Add nlu core about pages
  docs/conf.py
  docs/core/about.rst
  docs/index.rst
  docs/nlu/about.rst
Labels: docs

#3222 refactor nlu test script
  rasa/nlu/test.py
  tests/nlu/base/test_evaluation.py
  tests/nlu/conftest.py
Labels: enhancement

#3525 remove late normalization
  rasa/core/policies/ensemble.py
  rasa/core/processor.py
  tests/core/test_ensemble.py
Labels: bug

#3520 Validate missing utterance templates
  CHANGELOG.rst
  rasa/core/domain.py
  rasa/train.py
  tests/core/test_agent.py
Labels: enhancement

#3531 Re-train only NLU/Core model if corresponding config parameters changed
  rasa/core/utils.py
  rasa/model.py
  rasa/train.py
  tests/core/test_model.py
Labels: enhancement

#3487 Use questionary buttons when interacting with assistant via the terminal
  CHANGELOG.rst
  rasa/cli/utils.py
  rasa/core/channels/console.py
  rasa/core/restore.py
  rasa/core/training/interactive.py
Labels: enhancement
