Repository RasaHQ/rasa, pull requests merged in 2020-12, with the labels that each got.

#7417 Correctly set slots in domain when just updating nlg.
  changelog/7417.bugfix.md
  data/test_domains/domain_with_categorical_slot.yml
  rasa/core/agent.py
  rasa/model.py
  rasa/shared/core/domain.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/test_model.py
Labels: type:bug :bug:

#7448 Fix Windows unit tests
  Makefile
Labels: status:ready-to-merge

#7266 Adding Release info to README
  README.md
Labels: status:ready-to-merge

#7410 improve warning message when entity misaligned
  rasa/nlu/extractors/extractor.py
Labels: status:ready-to-merge

#7418 Preserve domain slot ordering and multistrings while dumping
  changelog/7418.bugfix.md
  rasa/model.py
  rasa/shared/core/domain.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  tests/shared/core/test_domain.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#7452 use HTTPStatus constant
  rasa/server.py
  tests/test_server.py
Labels: status:ready-to-merge

#7404 Update confidence histograms for better readability
  changelog/7257.improvement.md
  docs/docs/testing-your-assistant.mdx
  docs/static/img/intent_confusion_matrix_example.png
  docs/static/img/intent_histogram_example.png
  rasa/utils/plotting.py
Labels: status:ready-to-merge

#7468 typo ci action
  .github/workflows/spellcheck.yml
Labels: status:ready-to-merge

#7486 fixed typo
  docs/docs/nlu-training-data.mdx
Labels: status:ready-to-merge, type:docs :book:

#7284 Poc bandit
  .github/change_filters.yml
  .github/workflows/continous-integration.yml
  .github/workflows/security-scans.yml
  Makefile
  bandit.yml
  changelog/7284.improvement.md
  poetry.lock
  pyproject.toml
  rasa/core/tracker_store.py
  rasa/core/utils.py
  rasa/shared/utils/io.py
Labels: area:rasa-oss/infrastructure :bullettrain_front:, status:ready-to-merge, type:maintenance :wrench:

#7509 [Unit tests] Don't load Poetry cache for Windows
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/security-scans.yml
Labels: status:ready-to-merge

#7471 Add test to verify that word boundaries are still needed for whitespace-tokenized languages
  changelog/7167.misc.md
  tests/nlu/featurizers/test_regex_featurizer.py
Labels: status:ready-to-merge

#7457 Cross val endpoint
  changelog/7408.bugfix.md
  changelog/7408.feature.md
  changelog/7408.improvement.md
  docs/static/spec/rasa.yml
  rasa/nlu/test.py
  rasa/server.py
  rasa/train.py
  tests/conftest.py
  tests/nlu/test_evaluation.py
  tests/test_server.py
Labels: status:ready-to-merge

#7195 Accept multiple domain files in Rasa X local mode
  rasa/cli/arguments/x.py
  rasa/cli/x.py
  tests/cli/test_rasa_x.py
Labels: area:rasa-oss :ferris_wheel:, status:ready-to-merge

#7397 rasa train --dry-run
  changelog/7397.improvement.md
  rasa/cli/arguments/train.py
  rasa/cli/interactive.py
  rasa/cli/scaffold.py
  rasa/cli/train.py
  rasa/model.py
  rasa/server.py
  rasa/train.py
  tests/cli/test_rasa_interactive.py
  tests/cli/test_rasa_train.py
  tests/conftest.py
  tests/test_server.py
  tests/test_train.py
Labels: status:ready-to-merge

#7268 FloatSlot._as_feature should return unambiguous values
  changelog/7244.bugfix.md
  poetry.lock
  pyproject.toml
  rasa/constants.py
  rasa/shared/core/slots.py
  rasa/version.py
  tests/shared/core/test_slots.py
Labels: status:ready-to-merge

#7521 Checkout a custom branch of training data repo for model regression tests
  .github/configs/mr-test-example.yaml
  .github/scripts/mr_generate_summary.py
  .github/scripts/mr_publish_results.py
  .github/templates/model_regression_test_config_to_json.tmpl
  .github/templates/model_regression_test_results.tmpl
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
Labels: status:ready-to-merge

#7499 Merge 2.1.3 to master
  CHANGELOG.mdx
  data/test_domains/domain_with_categorical_slot.yml
  data/test_nlg/test_responses.yml
  rasa/core/agent.py
  rasa/model.py
  rasa/shared/core/domain.py
  rasa/shared/importers/importer.py
  rasa/shared/importers/rasa.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/test_model.py
  tests/shared/core/test_domain.py
  tests/shared/importers/test_importer.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#7529 Default slots
  changelog/7529.bugfix.md
  changelog/7529.removal.md
  data/test_config/max_hist_config.yml
  data/test_config/no_max_hist_config.yml
  data/test_config/stack_config.yml
  data/test_config/ted_random_seed.yaml
  data/test_domains/default_with_slots.yml
  data/test_domains/default_with_slots_and_no_actions.yml
  data/test_stories/stories_defaultdomain.md
  data/test_trackers/tracker_moodbot.json
  data/test_yaml_stories/stories_defaultdomain.yml
  rasa/core/agent.py
  rasa/core/policies/ensemble.py
  rasa/model.py
  rasa/shared/core/domain.py
  rasa/shared/core/slots.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/test_actions.py
  tests/core/test_agent.py
  tests/core/test_model.py
  tests/core/test_processor.py
  tests/core/test_training.py
  tests/shared/core/test_dialogues.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
  tests/test_server.py
  tests/test_train.py
Labels: status:ready-to-merge

#7547 merge 2.1.x to master
  changelog/7529.bugfix.md
  changelog/7529.removal.md
  data/test_config/max_hist_config.yml
  data/test_config/no_max_hist_config.yml
  data/test_config/stack_config.yml
  data/test_config/ted_random_seed.yaml
  data/test_domains/default_with_slots.yml
  data/test_domains/default_with_slots_and_no_actions.yml
  data/test_stories/stories_defaultdomain.md
  data/test_trackers/tracker_moodbot.json
  data/test_yaml_stories/stories_defaultdomain.yml
  docs/docs/nlu-training-data.mdx
  rasa/core/agent.py
  rasa/core/policies/ensemble.py
  rasa/model.py
  rasa/shared/core/domain.py
  rasa/shared/core/slots.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/test_actions.py
  tests/core/test_agent.py
  tests/core/test_model.py
  tests/core/test_processor.py
  tests/core/test_training.py
  tests/shared/core/test_dialogues.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
  tests/test_server.py
  tests/test_train.py
Labels: status:ready-to-merge

#7436 Use tokens for story structure validation
  changelog/7436.improvement.md
  docs/docs/command-line-interface.mdx
  docs/docs/setting-up-ci-cd.mdx
  rasa/cli/data.py
  rasa/core/featurizers/single_state_featurizer.py
  rasa/core/training/story_conflict.py
  rasa/shared/importers/autoconfig.py
  rasa/shared/nlu/training_data/features.py
  rasa/validator.py
  tests/cli/test_rasa_data.py
  tests/test_validator.py
Labels: type:maintenance :wrench:

#7546 Typo event broker
  docs/docs/event-brokers.mdx
  docs/docs/how-to-deploy.mdx
Labels: status:ready-to-merge

#7558 Review comments2
  rasa/shared/core/events.py
Labels: status:ready-to-merge

#7542 Load Poetry cache on Windows
  .github/workflows/continous-integration.yml
Labels: status:ready-to-merge

#7549 added custom actions url
  docs/docs/custom-actions.mdx
Labels: status:ready-to-merge, type:docs :book:

#7570 Prepare release 2.2.0
  CHANGELOG.mdx
  bandit.yml
  changelog/3998.improvement.md
  changelog/6410.removal.md
  changelog/6804.bugfix.md
  changelog/6971.feature.md
  changelog/7167.misc.md
  changelog/7232.improvement.md
  changelog/7244.bugfix.md
  changelog/7257.improvement.md
  changelog/7284.improvement.md
  changelog/7306.bugfix.md
  changelog/7313.doc.md
  changelog/7397.improvement.md
  changelog/7407.bugfix.md
  changelog/7408.bugfix.md
  changelog/7408.feature.md
  changelog/7408.improvement.md
  changelog/7422.bugfix.md
  changelog/7436.improvement.md
  changelog/7458.removal.md
  changelog/7495.removal.md
  changelog/7496.feature.md
  changelog/7529.bugfix.md
  changelog/7529.removal.md
  poetry.lock
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7585 correctly replace database name in query
  changelog/7585.bugfix.md
  rasa/core/tracker_store.py
  tests/core/test_tracker_stores.py
Labels: status:ready-to-merge

#7564 ignore SlotSets for requested slots
  changelog/7557.bugfix.md
  rasa/core/actions/forms.py
  tests/core/actions/test_forms.py
Labels: status:ready-to-merge

#7582 remove private registry from pyproject.toml
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#7587 prepared release of version 2.2.1
  CHANGELOG.mdx
  changelog/7557.bugfix.md
  changelog/7585.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7612 Rasa x startup issues with Rasa Open Source 2.2.x and Rasa X < 0.35
  changelog/7592.bugfix.md
  rasa/cli/x.py
Labels: status:ready-to-merge

#7617 prepared release of version 2.2.2
  CHANGELOG.mdx
  changelog/7592.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7621 CI/CD Docs Updates
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/testing-your-assistant.mdx
  docs/static/img/train-test-github-action.png
Labels: status:ready-to-merge, type:docs :book:

#7622 correctly retrieve intent ranking from useruttered event
  changelog/7622.bugfix.md
  rasa/core/actions/action.py
  tests/core/test_actions.py
Labels: status:ready-to-merge

#7601 Removed group_id from Kafka Producer's Description
  changelog/7601.misc.md
  rasa/core/brokers/kafka.py
Labels: type:docs :book:
