Repository RasaHQ/rasa, pull requests merged in 2020-04, with the labels that each got.

#5537 WIP - Update to Documentation - Bert
  docs/index.rst
  docs/nlu/components.rst
  docs/nlu/using-bert.rst
Labels: area:Rasa Open Source

#5639 fix typo in forms doc
  docs/core/forms.rst
Labels: type:docs :book:

#5650 docs removal
  docs/index.rst
  docs/nlu/using-bert.rst
Labels: type:docs :book:

#5611 Metada on session start action
  changelog/5574.bugfix.rst
  rasa/core/processor.py
  tests/core/test_processor.py
Labels: priority:normal

#5578 Implemented get_output_channel() fn for SocketIO Channel
  changelog/5578.improvement.rst
  docs/_static/spec/rasa.yml
  rasa/core/channels/socketio.py
Labels: priority:normal
