Repository RasaHQ/rasa, pull requests merged in 2020-10, with the labels that each got.

#6789 Updated Convo Pattern & Form Docs to Use Example Bots
  docs/docs/business-logic.mdx
  docs/docs/chitchat-faqs.mdx
  docs/docs/contextual-conversations.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/forms.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/unexpected-input.mdx
  examples/concertbot/actions/actions.py
  examples/concertbot/config.yml
  examples/concertbot/data/nlu.yaml
  examples/concertbot/data/stories.yaml
  examples/concertbot/domain.yml
Labels: status:ready-to-merge

#6749 Two stage fallback policy actions deprecated
  docs/docs/fallback-handoff.mdx
  docs/docs/migration-guide.mdx
  examples/rules/data/rules.yml
  rasa/core/actions/action.py
  rasa/shared/core/constants.py
Labels: status:ready-to-merge

#6817 unfeaturized slots
  changelog/6809.improvement.md
  changelog/6809.removal.md
  data/test_domains/people_form.yml
  data/test_domains/query_form.yml
  data/test_domains/restaurant_form.yml
  data/test_domains/travel_form.yml
  docs/docs/business-logic.mdx
  docs/docs/domain.mdx
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/unexpected-input.mdx
  docs/docs/writing-stories.mdx
  examples/formbot/domain.yml
  examples/knowledgebasebot/domain.yml
  examples/reminderbot/domain.yml
  examples/rules/domain.yml
  rasa/shared/constants.py
  rasa/shared/core/domain.py
  rasa/shared/core/slots.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_slots.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#6722 Update responses docs
  docs/docs/components.mdx
  docs/docs/domain.mdx
  docs/docs/glossary.mdx
  docs/docs/nlg.mdx
  docs/docs/responses.mdx
Labels: status:ready-to-merge, type:docs :book:

#6880 also check for Button href in docs
  docs/docs/installation.mdx
  tests/docs/test_docs_use_base_url.py
Labels: status:ready-to-merge

#6882 Update migration guide
  docs/docs/migration-guide.mdx
  docs/docs/policies.mdx
Labels: status:ready-to-merge

#6835 rename form validation event
  changelog/6463.removal.md
  rasa/core/actions/forms.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/rule_policy.py
  rasa/core/training/interactive.py
  rasa/shared/core/constants.py
  rasa/shared/core/events.py
  rasa/shared/core/trackers.py
  tests/core/actions/test_forms.py
  tests/core/policies/test_rule_policy.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
Labels: status:ready-to-merge

#6878 Update tensorflow-hub and tensorflow-probability
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#6877 Update business-logic.mdx to specify form as dictionary not a list
  docs/docs/business-logic.mdx
Labels: status:ready-to-merge

#6839 fix converter tool to convert test stories to yaml
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/shared/core/training_data/loading.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/data.py
  rasa/utils/converter.py
  tests/cli/test_rasa_data.py
  tests/core/training/converters/test_story_markdown_to_yaml_converter.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#6822 Docs accessibility
  CHANGELOG.mdx
  docs/docs/architecture-img.png
  docs/docs/architecture.mdx
  docs/docs/business-logic.mdx
  docs/docs/component-lifecycle-img.png
  docs/docs/components.mdx
  docs/docs/connectors/cisco-webex-teams.mdx
  docs/docs/connectors/hangouts.mdx
  docs/docs/connectors/slack.mdx
  docs/docs/contextual-conversations.mdx
  docs/docs/conversation-driven-development.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/glossary.mdx
  docs/docs/how-to-deploy.mdx
  docs/docs/installation.mdx
  docs/docs/migrate-from/dialogflow_export.png
  docs/docs/migrate-from/dialogflow_export_2.png
  docs/docs/migrate-from/google-dialogflow-to-rasa.mdx
  docs/docs/migrate-from/luis_export.png
  docs/docs/migrate-from/microsoft-luis-to-rasa.mdx
  docs/docs/model-configuration.mdx
  docs/docs/nlu-training-data.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/stories.mdx
  docs/docs/tracker-stores.mdx
  docs/docs/training-data-format.mdx
  docs/docs/tuning-your-model.mdx
  docs/docs/unexpected-input.mdx
  docs/docs/writing-stories.mdx
  docs/docusaurus.config.js
  docs/static/img/contextual_interjection.png
  docs/static/img/generic_interjection.png
  docs/static/img/generic_interjection_handled.png
  docs/static/img/greet_interjection.png
  docs/static/img/intent_mappings.png
  docs/static/img/knowledge-base-example.png
  docs/static/img/memoization_policy_convo.png
Labels: status:ready-to-merge

#6854 Automated policy migration
  docs/docs/policies.mdx
  docs/docs/telemetry/events.json
  rasa/cli/data.py
  rasa/core/config.py
  rasa/core/constants.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/fallback.py
  rasa/core/policies/rule_policy.py
  rasa/core/policies/two_stage_fallback.py
  rasa/nlu/classifiers/fallback_classifier.py
  rasa/shared/core/domain.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  rasa/shared/utils/io.py
  rasa/utils/io.py
  tests/cli/conftest.py
  tests/cli/test_rasa_data.py
  tests/core/test_config.py
  tests/core/test_ensemble.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#6825 Add architecture diagram and nlu/core description to Into
  docs/docs/arch-overview.mdx
  docs/docs/introduction.mdx
  docs/sidebars.js
  docs/static/img/architecture.png
Labels: status:ready-to-merge, type:docs :book:

#6831 Fix data validation responseselector
  data/test_domains/selectors.yml
  data/test_selectors/nlu.md
  data/test_selectors/nlu.yml
  data/test_selectors/responses.md
  rasa/validator.py
  tests/test_validator.py
Labels: status:ready-to-merge

#6901 rename to 'slots_to_validate'
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
Labels: status:ready-to-merge

#6905 form deactivations during validation
  rasa/core/actions/forms.py
  tests/core/actions/test_forms.py
Labels: status:ready-to-merge

#6890 Fixed bug with conversion of MD test stories
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/story_step_builder.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  tests/core/training/converters/test_story_markdown_to_yaml_converter.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
Labels: status:ready-to-merge

#6908 add the variables import back in
  docs/docs/tracker-stores.mdx
  tests/docs/test_docs_header_hierarchy.py
Labels: status:ready-to-merge

#6887 Form validation doc update
  changelog/6819.doc.md
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
Labels: status:ready-to-merge

#6920 Rules docs update
  docs/docs/policies.mdx
Labels: status:ready-to-merge

#6912 dump domain as yaml including the training data version
  rasa/shared/core/domain.py
  rasa/shared/utils/io.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#6884 remove notes about release alpha in docs
  docs/docs/installation.mdx
  docs/docs/prototype-an-assistant.mdx
Labels: status:ready-to-merge

#6891 Omit line anchors in links to functions because it is error prone
  docs/docs/components.mdx
  rasa/core/nlg/callback.py
Labels: type:enhancement :sparkles:

#6925 Delete model directory if it wasn't loaded correctly, when fetching from server
  rasa/core/agent.py
Labels: status:ready-to-merge

#6934 enable conversation sessions by default
  changelog/6934.removal.md
  docs/docs/migration-guide.mdx
  rasa/constants.py
  rasa/shared/constants.py
  rasa/shared/core/domain.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#6936 Delete model directory if it wasn't loaded when fetching from server (1.10)
  changelog/3597.bugfix.rst
  rasa/core/agent.py
Labels: status:ready-to-merge

#6821 AssistantBuilder component for Rasa Playground; UI improvements for Playground
  docs/docs/prototype-an-assistant.mdx
  docs/package.json
  docs/sidebars.js
  docs/static/js/rasa-chatblock.min.js
  docs/themes/theme-custom/theme/AssistantBuilder/index.jsx
  docs/themes/theme-custom/theme/AssistantBuilder/styles.module.css
  docs/themes/theme-custom/theme/CodeBlock/index.jsx
  docs/themes/theme-custom/theme/Playground/index.jsx
  docs/themes/theme-custom/theme/Playground/styles.module.css
  docs/themes/theme-custom/theme/Prototyper/button.jsx
  docs/themes/theme-custom/theme/Prototyper/download-button.jsx
  docs/themes/theme-custom/theme/Prototyper/prototyper.jsx
  docs/themes/theme-custom/theme/Prototyper/train-button.jsx
  docs/themes/theme-custom/theme/RasaButton/index.jsx
  docs/themes/theme-custom/theme/RasaButton/styles.module.css
  docs/yarn.lock
Labels: status:ready-to-merge, type:docs :book:

#6858 NLU-only Docs Page
  docs/docs/nlu-only.mdx
  docs/sidebars.js
Labels: status:ready-to-merge, type:docs :book:

#6888 Added reference to Rules bot example in rules doc
  docs/docs/rules.mdx
Labels: status:ready-to-merge

#6914 Export data from interactive learning broken
  changelog/6603.bugfix.md
  data/test_trackers/tracker_moodbot_with_new_utterances.json
  rasa/core/training/interactive.py
  rasa/shared/core/trackers.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/core/training_data/story_writer/markdown_story_writer.py
  rasa/shared/core/training_data/story_writer/story_writer.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  tests/core/test_policies.py
  tests/core/training/test_interactive.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
Labels: status:ready-to-merge

#6886 clean up docs todos
  .typo-ci.yml
  docs/docs/cheatsheet.mdx
  docs/docs/connectors/cisco-webex-teams.mdx
  docs/docs/connectors/custom-connectors.mdx
  docs/docs/connectors/facebook-messenger.mdx
  docs/docs/connectors/hangouts.mdx
  docs/docs/connectors/mattermost.mdx
  docs/docs/connectors/microsoft-bot-framework.mdx
  docs/docs/connectors/rocketchat.mdx
  docs/docs/connectors/slack.mdx
  docs/docs/connectors/telegram.mdx
  docs/docs/connectors/twilio.mdx
  docs/docs/connectors/your-own-website.mdx
  docs/docs/domain.mdx
  docs/docs/messaging-and-voice-channels.mdx
  docs/docs/writing-stories.mdx
  docs/sidebars.js
  examples/concertbot/domain.yml
Labels: status:ready-to-merge

#6929 rasa test core: check if model was provided
  changelog/6929.bugfix.md
  rasa/cli/test.py
  tests/cli/test_rasa_test.py
Labels: status:ready-to-merge

#6913 `rasa train nlu` accepts domain
  data/test_config/config_defaults.yml
  data/test_config/config_response_selector_minimal.yml
  data/test_nlu_no_responses/domain_with_only_responses.yml
  data/test_nlu_no_responses/nlu_no_responses.yml
  rasa/cli/arguments/default_arguments.py
  rasa/cli/arguments/train.py
  rasa/cli/train.py
  rasa/train.py
  tests/cli/test_rasa_train.py
  tests/test_train.py
Labels: status:ready-to-merge

#6803 [bugfix][WIP] Fix the bug of language supporting detection function of component
  changelog/6803.bugfix.md
  docs/docs/tracker-stores.mdx
  rasa/nlu/components.py
  tests/docs/test_docs_header_hierarchy.py
  tests/nlu/test_components.py
Labels: status:ready-to-merge

#6940 fix collecting fingerprint for action_listen
  rasa/core/training/training.py
  tests/core/policies/test_rule_policy.py
Labels: status:ready-to-merge

#6928 Expose YAML dict structure used by RasaYAMLWriter
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#6859 Update outdated docs content
  docs/docs/event-brokers.mdx
  docs/docs/forms.mdx
  docs/docs/generating-nlu-data.mdx
  docs/docs/glossary.mdx
  docs/docs/how-to-deploy.mdx
  docs/docs/responses.mdx
Labels: status:ready-to-merge

#6724 nlu training data docs updates
  docs/docs/components.mdx
  docs/docs/nlu-training-data.mdx
  docs/docs/training-data-format.mdx
  rasa/core/nlg/callback.py
Labels: status:ready-to-merge, type:docs :book:

#6947 Outdated docs
  docs/docs/arch-overview.mdx
  docs/docs/domain.mdx
  docs/docs/model-configuration.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6725 Docs workshop mark maxime
  docs/docs/components.mdx
  docs/docs/policies.mdx
Labels: status:ready-to-merge, type:docs :book:

#6946 Support OR for Rules in YAML
  data/test_yaml_stories/rules_without_stories.yml
  rasa/utils/schemas/stories.yml
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#6931 Do not filter training data in model.py but on component side
  changelog/6919.bugfix.md
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/classifiers/keyword_intent_classifier.py
  rasa/nlu/extractors/crf_entity_extractor.py
  rasa/nlu/extractors/mitie_entity_extractor.py
  rasa/nlu/extractors/regex_entity_extractor.py
  rasa/nlu/model.py
  rasa/shared/nlu/training_data/message.py
  rasa/shared/nlu/training_data/training_data.py
  tests/shared/nlu/training_data/test_message.py
Labels: status:ready-to-merge

#6942 Merge 1.10.x into master
  changelog/3597.bugfix.md
  changelog/6755.bugfix.md
  changelog/6900.improvement.md
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  rasa/nlu/tokenizers/convert_tokenizer.py
  rasa/utils/common.py
  rasa/utils/train_utils.py
  tests/nlu/tokenizers/test_lm_tokenizer.py
Labels: status:ready-to-merge

#6945 pre-release docs updates
  docs/docs/docker/building-in-docker.mdx
  docs/docs/http-api.mdx
  docs/docs/installation.mdx
  docs/docs/training-data-importers.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: status:ready-to-merge

#6952 fix comment exploding autoconfig
  data/test_config/config_with_comment_between_suggestions.yml
  rasa/shared/importers/autoconfig.py
  tests/shared/importers/test_autoconfig.py
Labels: status:ready-to-merge

#6949 Copyedits playground
  docs/docs/how-to-deploy.mdx
  docs/docs/installation.mdx
  docs/docs/introduction.mdx
  docs/docs/playground.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6954 Changes for YAMLStoryWriter
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/shared/core/training_data/story_writer/markdown_story_writer.py
  rasa/shared/core/training_data/story_writer/story_writer.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  rasa/shared/core/training_data/structures.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
  tests/test_test.py
Labels: status:ready-to-merge

#6953 Properly raise yaml errors when parser fails to read story / rule files / domain
  rasa/cli/interactive.py
  rasa/cli/run.py
  rasa/cli/scaffold.py
  rasa/cli/test.py
  rasa/nlu/config.py
  rasa/nlu/extractors/entity_synonyms.py
  rasa/server.py
  rasa/shared/constants.py
  rasa/shared/core/domain.py
  rasa/shared/core/slots.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/story_step_builder.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/exceptions.py
  rasa/shared/nlu/training_data/formats/markdown.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/utils/io.py
  rasa/shared/utils/validation.py
  tests/cli/test_rasa_data.py
  tests/conftest.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_slots.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
  tests/shared/utils/test_validation.py
  tests/test_server.py
  tests/utilities.py
Labels: status:ready-to-merge

#6805 Filter response templates for retrieval intents in domain during sync
  changelog/6805.bugfix.md
  data/test_domains/mixed_retrieval_intents.yml
  rasa/shared/core/domain.py
  rasa/shared/importers/importer.py
  tests/shared/core/test_domain.py
  tests/shared/importers/test_importer.py
Labels: status:ready-to-merge

#6941 Make sure that compare the same fields for schedule version
  .github/templates/README.md
  .github/templates/model_regression_test_results.tmpl
Labels: status:ready-to-merge

#6975 disable searchbox shortcut in docs
  docs/docusaurus.config.js
  docs/themes/theme-custom/index.js
  docs/themes/theme-custom/styles.css
Labels: status:ready-to-merge

#6974 [Port for 2.0.x ] Make sure that compare the same fields for schedule version
  .github/templates/README.md
  .github/templates/model_regression_test_results.tmpl
Labels: status:ready-to-merge

#6980 Merge 2.0.x
  CHANGELOG.mdx
  changelog/6805.bugfix.md
  changelog/6943.improvement.md
  docs/docs/fallback-handoff.mdx
  docs/docs/forms.mdx
  docs/docs/unexpected-input.mdx
  docs/docusaurus.config.js
  docs/themes/theme-custom/index.js
  docs/themes/theme-custom/styles.css
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
Labels: status:ready-to-merge

#7004 Correct missing mapping policy message
  rasa/core/policies/mapping_policy.py
Labels: status:ready-to-merge

#6760 Use multiprocessing for Pika event consumer
  changelog/6760.bugfix.md
  rasa/core/brokers/pika.py
  tests/core/test_broker.py
Labels: status:ready-to-merge

#6981 Backport pika fix
  changelog/6703.bugfix.rst
  rasa/core/brokers/pika.py
  tests/core/test_broker.py
Labels: status:ready-to-merge

#7017 prepared release of version 1.10.16
  CHANGELOG.rst
  changelog/6703.bugfix.rst
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7008 Don't use set-env in the CIs
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/vulnerability-scan.yml
Labels: status:ready-to-merge

#7006 Use gitleaks for detecting hardcoded secrets
  .github/workflows/security-scans.yml
Labels: status:ready-to-merge

#6986 Updated Slack Connector for new Events API
  changelog/6986.bugfix.md
  rasa/core/channels/slack.py
  tests/core/test_channels.py
Labels: status:ready-to-merge

#7024 Add Slack notifications for schedule workflows
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/security-scans.yml
  .github/workflows/vulnerability-scan.yml
Labels: status:ready-to-merge

#6995 Merge 1.10.x into master
  CHANGELOG.mdx
  poetry.lock
  rasa/core/test.py
Labels: status:ready-to-merge

#7021 Document `rasa data validate` in CLI docs
  docs/docs/command-line-interface.mdx
  docs/docs/setting-up-ci-cd.mdx
Labels: status:ready-to-merge, type:docs :book:

#7018 Create correct KafkaProducer for PLAINTEXT and SASL_SSL security protocols.
  changelog/7018.bugfix.md
  rasa/core/brokers/kafka.py
Labels: status:ready-to-merge

#7028 Docs update mechanism supports duplicate versions
  scripts/push_docs_to_branch.sh
Labels: status:ready-to-merge

#6776 configure algolia search
  docs/docusaurus.config.js
  docs/themes/theme-custom/index.js
  docs/themes/theme-custom/styles.css
Labels: status:ready-to-merge

#7030 Remove Slack notifications for gitleaks
  .github/workflows/security-scans.yml
Labels: status:ready-to-merge

#6916 Added Language Support Page to 2.0 Docs
  docs/docs/language-support.mdx
  docs/sidebars.js
Labels: status:ready-to-merge, type:docs :book:

#6979 Return all sessions for GET /story
  changelog/6860.improvement.md
  docs/static/spec/rasa.yml
  rasa/core/exporter.py
  rasa/core/processor.py
  rasa/core/tracker_store.py
  rasa/core/training/interactive.py
  rasa/core/utils.py
  rasa/server.py
  rasa/shared/core/events.py
  rasa/shared/core/trackers.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  tests/cli/test_rasa_export.py
  tests/conftest.py
  tests/core/test_exporter.py
  tests/core/test_tracker_stores.py
  tests/shared/core/test_events.py
  tests/shared/core/test_trackers.py
  tests/test_server.py
Labels: status:ready-to-merge

#6470 Switch to mypy part0
  .gitignore
  CONTRIBUTING.md
  Makefile
  README.md
  changelog/6470.misc.md
  poetry.lock
  pyproject.toml
  rasa/__main__.py
  rasa/cli/train.py
  rasa/cli/x.py
  rasa/core/actions/loops.py
  rasa/core/channels/botframework.py
  rasa/core/channels/channel.py
  rasa/core/channels/facebook.py
  rasa/core/channels/hangouts.py
  rasa/core/channels/mattermost.py
  rasa/core/channels/rasa_chat.py
  rasa/core/channels/rest.py
  rasa/core/channels/rocketchat.py
  rasa/core/channels/slack.py
  rasa/core/channels/telegram.py
  rasa/core/channels/twilio.py
  rasa/core/channels/webexteams.py
  rasa/core/featurizers/single_state_featurizer.py
  rasa/core/nlg/generator.py
  rasa/core/nlg/template.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/rule_policy.py
  rasa/core/policies/ted_policy.py
  rasa/core/training/interactive.py
  rasa/jupyter.py
  rasa/model.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/extractors/spacy_entity_extractor.py
  rasa/nlu/model.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/tokenizers/spacy_tokenizer.py
  rasa/nlu/utils/spacy_utils.py
  rasa/server.py
  rasa/shared/core/domain.py
  rasa/shared/core/trackers.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  rasa/shared/core/training_data/story_writer/story_writer.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  rasa/shared/core/training_data/structures.py
  rasa/shared/nlu/training_data/formats/markdown_nlg.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/message.py
  rasa/shared/nlu/training_data/training_data.py
  rasa/shared/utils/common.py
  rasa/utils/tensorflow/models.py
  setup.cfg
Labels: status:ready-to-merge

#6682 Add new glossary terms
  docs/docs/glossary.mdx
Labels: status:ready-to-merge, type:docs :book:

#7033 Fixes for story/rules reading and writing for both formats
  changelog/7033.bugfix.md
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/story_step_builder.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/core/training_data/structures.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
  tests/shared/core/training_data/test_structures.py
Labels: status:ready-to-merge

#7070 prepared release of version 2.0.1
  CHANGELOG.mdx
  changelog/7018.bugfix.md
  changelog/7033.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7074 avoid duplicating docs/ folder when releasing micros
  scripts/push_docs_to_branch.sh
Labels: status:ready-to-merge

#7012 enrich error messages from contradicting rules
  rasa/core/policies/rule_policy.py
Labels: status:ready-to-merge

#7084 Fix deleted code block backticks in the rasa data validate docs part.
  docs/docs/command-line-interface.mdx
Labels: status:ready-to-merge, type:bug :bug:, type:docs :book:

#7082 Prevent robots to follow redirects to legacy docs
  docs/docs/introduction.mdx
  docs/docs/migration-guide.mdx
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#7081 add robots.txt and redirection headers
  docs/_redirects
  docs/conf.py
  docs/robots.txt
  poetry.lock
Labels: status:ready-to-merge

#7020 Setting slots via API does not influence conversation
  changelog/6721.bugfix.md
  docs/static/spec/rasa.yml
  rasa/core/agent.py
  rasa/core/processor.py
  rasa/core/tracker_store.py
  rasa/server.py
  rasa/shared/core/events.py
  tests/core/test_processor.py
  tests/core/test_tracker_stores.py
  tests/shared/core/test_events.py
  tests/test_server.py
Labels: status:ready-to-merge

#6676 Multiple Sanic Workers Bugfix
  changelog/6629.bugfix.md
  rasa/core/utils.py
  tests/core/test_utils.py
Labels: status:ready-to-merge

#7097 Bump theme to 0.8.2, configure `rootEditUrl`
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: status:ready-to-merge

#6976 rebase: refactor test your assistant docs
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/testing-your-assistant.mdx
Labels: status:ready-to-merge

#7104 Merge 2.0.x master
  docs/plugins/program_output.js
Labels: status:ready-to-merge

#6999 Redirections Redux
  docs/netlify.toml
  docs/package.json
  docs/static/_redirects
Labels: type:docs :book:

#7105 Hotfix: tracking consent in docs
  docs/plugins/google-tagmanager/index.js
Labels: status:ready-to-merge

#7102 Change the default model weights for HFTransformersNLP
  changelog/7102.improvement.md
  docs/docs/components.mdx
  rasa/nlu/utils/hugging_face/registry.py
  tests/nlu/test_train.py
  tests/nlu/tokenizers/test_lm_tokenizer.py
  tests/nlu/utils/test_hf_transformers.py
Labels: status:ready-to-merge

#7112 Update formbot to use new validation action
  changelog/7108.bugfix.rst
  examples/formbot/actions/actions.py
  examples/formbot/domain.yml
Labels: status:ready-to-merge

#6978 Entity Roles and Groups influence dialogue predictions
  changelog/5715.improvement.md
  data/test_domains/travel_form.yml
  docs/docs/domain.mdx
  docs/docs/nlu-training-data.mdx
  rasa/core/featurizers/single_state_featurizer.py
  rasa/shared/core/constants.py
  rasa/shared/core/domain.py
  rasa/shared/core/events.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/utils/schemas/domain.yml
  rasa/utils/schemas/stories.yml
  tests/core/test_featurizer.py
  tests/shared/core/test_domain.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#7115 Rename 7108.bugfix.rst to 7108.bugfix.md
  changelog/7108.bugfix.md
Labels: status:ready-to-merge

#7116 Update playground content
  docs/docs/playground.mdx
Labels: status:ready-to-merge

#6910 add validation of docstrings (pydocstyle)
  .github/workflows/continous-integration.yml
  Makefile
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: status:ready-to-merge

#7035 check if `ActionExecutionRejected` should be thrown after custom action for slot validations was called
  changelog/6977.improvement.md
  docs/docs/forms.mdx
  rasa/core/actions/forms.py
  rasa/core/policies/ensemble.py
  rasa/core/processor.py
  tests/core/actions/test_forms.py
  tests/core/test_processor.py
Labels: status:ready-to-merge

#7128 backport shared codeowner
  CODEOWNERS
Labels: status:ready-to-merge

#7126 Backport docstring validation to 2.0.x
  .github/workflows/continous-integration.yml
  Makefile
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: status:ready-to-merge

#7095 Fixes a bug with `rasa data split nlu`
  changelog/6582.bugfix.md
  rasa/shared/nlu/training_data/training_data.py
  tests/shared/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge

#7089 Restrict acceptable values for model_url parameter of ConveRTTokenizer
  changelog/7089.bugfix.md
  docs/docs/components.mdx
  rasa/nlu/tokenizers/convert_tokenizer.py
  rasa/nlu/utils/__init__.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/test_utils.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
Labels: status:ready-to-merge

#7135 Prepare release 2.0.3
  CHANGELOG.mdx
  changelog/7089.bugfix.md
  changelog/7108.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7137 Merge 2.0.x to master
  CHANGELOG.mdx
  CODEOWNERS
  docs/docs/components.mdx
  docs/docs/playground.mdx
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/testing-your-assistant.mdx
  examples/formbot/actions/actions.py
  examples/formbot/domain.yml
  pyproject.toml
  rasa/nlu/tokenizers/convert_tokenizer.py
  rasa/nlu/utils/__init__.py
  rasa/version.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/test_utils.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
Labels: status:ready-to-merge

#7080 Make converter support response key for test stories
  changelog/7034.bugfix.md
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  tests/core/training/converters/test_story_markdown_to_yaml_converter.py
Labels: status:ready-to-merge

#7123 Adapt the training data reader and emulator for wit.ai to their latest format
  changelog/6474.improvement.md
  data/examples/wit/demo-flights.json
  data/test/wit_converted_to_rasa.json
  docs/docs/migrate-from/facebook-wit-ai-to-rasa.mdx
  rasa/nlu/emulators/dialogflow.py
  rasa/nlu/emulators/emulator.py
  rasa/nlu/emulators/luis.py
  rasa/nlu/emulators/no_emulator.py
  rasa/nlu/emulators/wit.py
  rasa/shared/nlu/training_data/formats/wit.py
  rasa/shared/nlu/training_data/loading.py
  tests/nlu/emulators/test_wit.py
  tests/shared/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge
