Repository RasaHQ/rasa, pull requests merged in 2020-09, with the labels that each got.

#6551 fix fingerprinting of domains with `triggers: `
  rasa/core/domain.py
  rasa/model.py
  tests/core/test_model.py
Labels: status:ready-to-merge

#6575 No warning during prediction if Response Selector was not trained
  rasa/nlu/selectors/response_selector.py
Labels: status:ready-to-merge

#6576 `rasa.shared` code owners + additional test
  CODEOWNERS
  tests/shared/utils/test_common.py
Labels: status:ready-to-merge

#6574 Bump pydoc-markdown to the latest version
  docs/pydoc-markdown.yml
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#6567 Better handling of sequences longer than maximum sequence length for BERT style models
  changelog/6222.bugfix.md
  rasa/nlu/constants.py
  rasa/nlu/utils/hugging_face/hf_transformers.py
  tests/nlu/utils/test_hf_transformers.py
Labels: status:ready-to-merge

#6577 Remove BILOU tag prefix from role and group labels
  changelog/6577.bugfix.md
  rasa/nlu/extractors/extractor.py
  tests/nlu/extractors/test_extractor.py
Labels: status:ready-to-merge

#6493 Added version numbers to Rasa examples' training data
  examples/concertbot/data/nlu.yaml
  examples/concertbot/data/rules.yaml
  examples/concertbot/data/stories.yaml
  examples/formbot/data/nlu.yml
  examples/formbot/data/rules.yml
  examples/formbot/data/stories.yml
  examples/knowledgebasebot/data/nlu.yaml
  examples/knowledgebasebot/data/rules.yaml
  examples/moodbot/data/nlu.yml
  examples/moodbot/data/rules.yml
  examples/moodbot/data/stories.yml
  examples/reminderbot/data/nlu.yml
  examples/reminderbot/data/rules.yml
  examples/rules/data/nlu.yml
  examples/rules/data/rules.yml
  tests/examples/test_example_bots_training_data.py
Labels: status:ready-to-merge

#6515 reorganize existing content on policies page
  docs/docs/policies.mdx
Labels: type:docs :book:

#6563 Dense dimension sparse input
  changelog/6555.improvement.md
  docs/docs/components/intent-classifiers.mdx
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/selectors/response_selector.py
Labels: status:ready-to-merge

#6595 polish file concatenation
  tests/test_server.py
Labels: status:ready-to-merge

#6586 add custom to nlg spec
  rasa/core/nlg/callback.py
  tests/core/test_nlg.py
Labels: status:ready-to-merge

#6472 Keep latest_input_channel when triggering intents
  changelog/6472.improvement.md
  rasa/core/events/__init__.py
  rasa/core/processor.py
  tests/core/test_processor.py
Labels: status:ready-to-merge

#6590 Added ability to mix NLU and Stories in one file
  data/test_mixed_yaml_training_data/training_data.yml
  pyproject.toml
  rasa/constants.py
  rasa/core/training/story_reader/yaml_story_reader.py
  rasa/nlu/training_data/formats/rasa_yaml.py
  rasa/utils/schemas/domain.yml
  rasa/utils/schemas/nlu.yml
  rasa/utils/schemas/responses.yml
  rasa/utils/schemas/stories.yml
  rasa/utils/validation.py
  tests/core/training/story_reader/test_yaml_story_reader.py
  tests/nlu/training_data/formats/test_rasa_yaml.py
  tests/test_data.py
Labels: status:ready-to-merge

#6589 Add option 'use_lemma' to CountVectorsFeaturizer
  changelog/6536.feature.md
  docs/docs/components/featurizers.mdx
  rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
  tests/nlu/featurizers/test_count_vectors_featurizer.py
Labels: status:ready-to-merge

#6612 Exclude FallbackClassifier from core featurization
  rasa/nlu/classifiers/fallback_classifier.py
Labels: status:ready-to-merge

#6594 Change forms in domain.yml to be dicts
  changelog/6535.bugfix.md
  data/test_domains/form.yml
  docs/docs/prototype-an-assistant.mdx
  examples/formbot/domain.yml
  examples/rules/domain.yml
  rasa/constants.py
  rasa/core/domain.py
  rasa/utils/schemas/domain.yml
  tests/core/actions/test_forms.py
  tests/core/test_actions.py
  tests/core/test_domain.py
Labels: status:ready-to-merge

#6444 Configure external Docusaurus theme
  .typo-ci.yml
  docs/.gitignore
  docs/babel.config.js
  docs/docs/index.mdx
  docs/docs/installation.mdx
  docs/docs/prototype-an-assistant.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/plugins/google-tagmanager/index.js
  docs/scripts/compile_included_sources.js
  docs/scripts/compile_program_outputs.js
  docs/scripts/compile_variables.js
  docs/scripts/copy_md_files.js
  docs/sidebars.js
  docs/src/components/prototyper/download-button.jsx
  docs/src/components/prototyper/prototyper.jsx
  docs/src/components/prototyper/train-button.jsx
  docs/src/components/redoc.jsx
  docs/src/css/custom.css
  docs/src/pages/api/index.jsx
  docs/src/theme/prism-include-languages.js
  docs/src/utils.js
  docs/static/img/logo.svg
  docs/static/img/rasa-logo.svg
  docs/themes/theme-custom/index.js
  docs/themes/theme-custom/theme/CodeBlock/index.jsx
  docs/themes/theme-custom/theme/Playground/index.jsx
  docs/themes/theme-custom/theme/Playground/styles.module.css
  docs/themes/theme-custom/theme/Prototyper/button.jsx
  docs/themes/theme-custom/theme/Prototyper/context.js
  docs/themes/theme-custom/theme/Prototyper/download-button.jsx
  docs/themes/theme-custom/theme/Prototyper/index.jsx
  docs/themes/theme-custom/theme/Prototyper/prototyper.jsx
  docs/themes/theme-custom/theme/Prototyper/train-button.jsx
  docs/themes/theme-custom/theme/ReactLiveScope/index.js
  docs/themes/theme-live-codeblock/theme/theme-context.js
  docs/yarn.lock
Labels: type:docs :book:

#6565 Fixed bugs with `rasa data convert`
  .typo-ci.yml
  data/test_nlg/responses.md
  docs/docs/command-line-interface.mdx
  docs/docs/migration-guide.mdx
  rasa/cli/arguments/data.py
  rasa/cli/data.py
  rasa/constants.py
  rasa/core/training/converters/__init__.py
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/core/training/story_writer/yaml_story_writer.py
  rasa/data.py
  rasa/nlu/training_data/converters/__init__.py
  rasa/nlu/training_data/converters/nlg_markdown_to_yaml_converter.py
  rasa/nlu/training_data/converters/nlu_markdown_to_yaml_converter.py
  rasa/nlu/utils/pattern_utils.py
  rasa/shared/nlu/training_data/formats/markdown_nlg.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/loading.py
  rasa/utils/converter.py
  tests/cli/test_rasa_data.py
  tests/core/training/converters/test_story_markdown_to_yaml_converter.py
  tests/core/training/story_writer/test_yaml_story_writer.py
  tests/nlu/training_data/converters/test_nlg_markdown_to_yaml_converter.py
  tests/nlu/training_data/converters/test_nlu_markdown_to_yaml_converter.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#6628 Add missing init file
  rasa/nlu/training_data/__init__.py
Labels: status:ready-to-merge

#6585 Update __init__.py
  rasa/core/events/__init__.py
Labels: status:ready-to-merge

#6611 Move actions.py -> actions/actions.py in rasa init
  changelog/5368.improvement.md
  docs/docs/business-logic.mdx
  docs/docs/command-line-interface.mdx
  docs/docs/docker/building-in-docker.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/how-to-deploy.mdx
  docs/docs/knowledge-bases.mdx
  docs/docs/running-action-server.mdx
  docs/docs/unexpected-input.mdx
  examples/concertbot/README.md
  examples/concertbot/actions/__init__.py
  examples/concertbot/actions/actions.py
  examples/formbot/README.md
  examples/formbot/actions/__init__.py
  examples/formbot/actions/actions.py
  examples/knowledgebasebot/README.md
  examples/knowledgebasebot/actions/__init__.py
  examples/knowledgebasebot/actions/actions.py
  examples/reminderbot/README.md
  examples/reminderbot/actions/__init__.py
  examples/reminderbot/actions/actions.py
  examples/rules/actions/__init__.py
  examples/rules/actions/actions.py
  rasa/cli/initial_project/actions/__init__.py
  rasa/cli/initial_project/actions/actions.py
  tests/cli/test_rasa_init.py
Labels: status:ready-to-merge

#6631 Sphinx styling
  docs/_static/css/custom.css
Labels: status:ready-to-merge

#6614 Use a more precise restore key for GH cache action
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
Labels: status:ready-to-merge

#6596 Setup pytest-timeout
  poetry.lock
  pyproject.toml
  pytest.ini
  tests/nlu/test_evaluation.py
  tests/test_train.py
Labels: status:ready-to-merge

#6644 name versions with .x instead of .0 in docs release script
  scripts/push_docs_to_branch.sh
Labels: status:ready-to-merge

#6591 New Response Selector training data format
  changelog/6591.improvement.md
  data/examples/rasa/demo-rasa-responses.md
  data/test/duplicate_intents_markdown/demo-rasa-intents-2.md
  data/test/duplicate_intents_markdown/demo-rasa-intents-3.md
  data/test_domains/default_retrieval_intents.yml
  data/test_responses/default.md
  docs/docs/components/selectors.mdx
  docs/docs/glossary.mdx
  docs/docs/migration-guide.mdx
  docs/docs/responses.mdx
  docs/docs/training-data-format.mdx
  examples/responseselectorbot/data/nlu.yml
  examples/responseselectorbot/data/responses.yml
  examples/responseselectorbot/data/rules.yml
  examples/responseselectorbot/domain.yml
  rasa/core/actions/action.py
  rasa/core/actions/forms.py
  rasa/core/constants.py
  rasa/core/processor.py
  rasa/core/training/interactive.py
  rasa/importers/importer.py
  rasa/importers/rasa.py
  rasa/nlu/constants.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/test.py
  rasa/shared/constants.py
  rasa/shared/core/constants.py
  rasa/shared/core/domain.py
  rasa/shared/nlu/training_data/training_data.py
  rasa/shared/nlu/training_data/util.py
  rasa/validator.py
  tests/core/test_actions.py
  tests/importers/test_importer.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_config.py
  tests/nlu/test_evaluation.py
  tests/shared/core/test_domain.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
  tests/shared/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge

#6600 rename action deactivate form
  changelog/6952.removal.md
  data/test_dialogues/formbot.json
  data/test_stories/stories_form.md
  docs/docs/default-actions.mdx
  docs/docs/forms.mdx
  examples/formbot/data/stories.yml
  rasa/constants.py
  rasa/core/actions/action.py
  rasa/core/channels/mattermost.py
  rasa/core/policies/fallback.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/mapping_policy.py
  rasa/core/tracker_store.py
  rasa/server.py
  rasa/shared/constants.py
  rasa/shared/core/constants.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/utils/io.py
  rasa/utils/common.py
  rasa/utils/train_utils.py
  tests/core/test_actions.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
  tests/shared/utils/test_io.py
  tests/utils/test_common.py
Labels: status:ready-to-merge

#6646 fix imports not using shared module directly
  docs/docs/domain.mdx
  docs/docs/training-data-importers.mdx
  rasa/core/featurizers/tracker_featurizers.py
  rasa/nlu/__init__.py
  rasa/nlu/schemas/__init__.py
  rasa/nlu/utils/__init__.py
  rasa/shared/utils/io.py
  rasa/utils/io.py
  tests/nlu/test_config.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/nlu/training_data/formats/test_markdown.py
  tests/shared/utils/test_io.py
Labels: status:ready-to-merge

#6622 Persist and load all RulePolicy attributes
  rasa/core/actions/action.py
  rasa/core/featurizers/tracker_featurizers.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/fallback.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/mapping_policy.py
  rasa/core/policies/memoization.py
  rasa/core/policies/policy.py
  rasa/core/policies/rule_policy.py
  rasa/core/policies/sklearn_policy.py
  rasa/core/policies/ted_policy.py
  rasa/core/policies/two_stage_fallback.py
  tests/core/policies/test_rule_policy.py
  tests/core/test_policies.py
Labels: status:ready-to-merge

#6657 `rasa.shared` wrap up
  rasa/cli/arguments/data.py
  rasa/cli/arguments/default_arguments.py
  rasa/cli/arguments/export.py
  rasa/cli/arguments/test.py
  rasa/cli/arguments/train.py
  rasa/cli/arguments/x.py
  rasa/cli/data.py
  rasa/cli/export.py
  rasa/cli/interactive.py
  rasa/cli/run.py
  rasa/cli/scaffold.py
  rasa/cli/shell.py
  rasa/cli/test.py
  rasa/cli/train.py
  rasa/cli/utils.py
  rasa/cli/visualize.py
  rasa/cli/x.py
  rasa/constants.py
  rasa/core/actions/action.py
  rasa/core/agent.py
  rasa/core/brokers/pika.py
  rasa/core/channels/mattermost.py
  rasa/core/featurizers/single_state_featurizer.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/fallback.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/mapping_policy.py
  rasa/core/utils.py
  rasa/model.py
  rasa/nlu/classifiers/fallback_classifier.py
  rasa/nlu/classifiers/keyword_intent_classifier.py
  rasa/nlu/config.py
  rasa/nlu/constants.py
  rasa/nlu/extractors/crf_entity_extractor.py
  rasa/nlu/extractors/duckling_http_extractor.py
  rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
  rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py
  rasa/nlu/model.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/test.py
  rasa/nlu/tokenizers/whitespace_tokenizer.py
  rasa/server.py
  rasa/shared/constants.py
  rasa/shared/nlu/constants.py
  rasa/shared/onstants.py
  rasa/test.py
  rasa/train.py
  rasa/validator.py
  tests/cli/test_rasa_test.py
  tests/core/actions/test_two_stage_fallback.py
  tests/core/test_model.py
  tests/nlu/classifiers/test_fallback_classifier.py
  tests/shared/importers/test_importer.py
  tests/shared/importers/test_multi_project.py
  tests/shared/importers/test_rasa.py
  tests/test_server.py
Labels: status:ready-to-merge

#5985 Model Checkpointing for DIET
  changelog/5985.improvement.md
  data/test_config/config_ted_policy_model_checkpointing.yml
  data/test_selectors/nlu.md
  data/test_selectors/responses.md
  docs/docs/components/intent-classifiers.mdx
  docs/docs/components/selectors.mdx
  docs/docs/policies.mdx
  rasa/constants.py
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/model.py
  rasa/nlu/selectors/response_selector.py
  rasa/shared/core/domain.py
  rasa/shared/importers/importer.py
  rasa/utils/tensorflow/constants.py
  rasa/utils/tensorflow/models.py
  tests/core/test_policies.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/selectors/test_selectors.py
Labels: status:ready-to-merge

#6648 update docs for new core featurization
  changelog/6296.removal.md
  docs/docs/migration-guide.mdx
  docs/docs/policies.mdx
Labels: status:ready-to-merge

#6624 remove out of date stuff part 1 (ella)
  .typo-ci.yml
  docs/docs/chitchat-faqs.mdx
  docs/docs/components/featurizers.mdx
  docs/docs/components/intent-classifiers.mdx
  docs/docs/components/selectors.mdx
  docs/docs/model-storage.mdx
  docs/docs/nlg.mdx
  docs/docs/policies.mdx
  docs/docs/prototype-an-assistant.mdx
  docs/docs/rasa-sdk-changelog.mdx
  docs/docs/responses.mdx
  docs/docs/retrieval-actions.mdx
  docs/docs/rules.mdx
  docs/docs/running-action-server.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docs/tracker-dispatcher.mdx
  docs/docs/training-data-format.mdx
  docs/docs/writing-stories.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6658 deprecate sklearn policy
  changelog/6658.removal.md
  rasa/core/policies/sklearn_policy.py
Labels: status:ready-to-merge

#6618 Remove out of date stuff pt. 1
  docs/docs/actions.mdx
  docs/docs/cdd.mdx
  docs/docs/command-line-interface.mdx
  docs/docs/custom-actions.mdx
  docs/docs/default-actions.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6617 Support metadata parsing for intents and intent examples
  docs/docs/components/custom-nlu-components.mdx
  docs/docs/training-data-format.mdx
  rasa/nlu/constants.py
  rasa/shared/nlu/constants.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/message.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#6604 Fix data split cli
  docs/docs/command-line-interface.mdx
  rasa/cli/data.py
  rasa/shared/core/training_data/loading.py
  rasa/shared/data.py
  rasa/shared/nlu/training_data/formats/readerwriter.py
  rasa/shared/nlu/training_data/training_data.py
  rasa/shared/nlu/training_data/util.py
  tests/cli/test_rasa_data.py
  tests/shared/importers/test_multi_project.py
  tests/shared/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge

#6661 refactor Rasa X local mode start
  rasa/cli/x.py
  rasa/shared/exceptions.py
  tests/cli/test_rasa_x.py
Labels: status:ready-to-merge

#6674 sort and deduplicate story events before adding them to NLU training data
  rasa/shared/core/events.py
  rasa/shared/importers/importer.py
  tests/shared/importers/test_importer.py
Labels: status:ready-to-merge

#6572 fix reading files for test core
  rasa/cli/test.py
  rasa/shared/data.py
Labels: status:ready-to-merge

#6660 Components back to one page
  .typo-ci.yml
  CHANGELOG.mdx
  changelog/5510.feature.md
  changelog/5957.feature.md
  changelog/6088.feature.md
  changelog/6453.removal.md
  docs/docs/business-logic.mdx
  docs/docs/chitchat-faqs.mdx
  docs/docs/components.mdx
  docs/docs/components/custom-nlu-components.mdx
  docs/docs/components/entity-extractors.mdx
  docs/docs/components/featurizers.mdx
  docs/docs/components/intent-classifiers.mdx
  docs/docs/components/language-models.mdx
  docs/docs/components/selectors.mdx
  docs/docs/components/tokenizers.mdx
  docs/docs/domain.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/generating-nlu-data.mdx
  docs/docs/migration-guide.mdx
  docs/docs/nlu-training-data.mdx
  docs/docs/retrieval-actions.mdx
  docs/docs/rules.mdx
  docs/docs/stories.mdx
  docs/docs/training-data-format.mdx
  docs/docs/tuning-your-model.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6640 turn no entity warning to debug log
  rasa/nlu/classifiers/diet_classifier.py
Labels: status:ready-to-merge

#6680 remove sdk content from rasa docs
  docs/docs/event-brokers.mdx
  docs/docs/events.mdx
  docs/docs/glossary.mdx
  docs/docs/knowledge-bases.mdx
  docs/docs/stories.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6636 Updated Docs Links to 2.0 structure
  data/configs_for_docs/example_for_suggested_config_after_train.yml
  data/test_config/config_empty_en_after_dumping.yml
  data/test_config/config_empty_en_after_dumping_core.yml
  data/test_config/config_empty_en_after_dumping_nlu.yml
  data/test_config/config_empty_en_after_dumping_windows.yml
  data/test_config/config_empty_en_after_dumping_windows_core.yml
  data/test_config/config_empty_en_after_dumping_windows_nlu.yml
  data/test_config/config_empty_fr_after_dumping.yml
  data/test_config/config_with_comments_after_dumping.yml
  data/test_config/stack_config.yml
  docs/docs/training-data-format.mdx
  examples/concertbot/README.md
  examples/formbot/README.md
  examples/knowledgebasebot/README.md
  examples/moodbot/README.md
  examples/reminderbot/README.md
  examples/reminderbot/actions/actions.py
  examples/reminderbot/credentials.yml
  examples/reminderbot/endpoints.yml
  examples/responseselectorbot/README.md
  rasa/cli/initial_project/actions/actions.py
  rasa/cli/initial_project/credentials.yml
  rasa/cli/initial_project/endpoints.yml
  rasa/cli/initial_project/tests/test_stories.yml
  rasa/cli/run.py
  rasa/cli/x.py
  rasa/core/actions/action.py
  rasa/core/channels/channel.py
  rasa/core/tracker_store.py
  rasa/run.py
  rasa/shared/constants.py
  rasa/shared/core/domain.py
  rasa/shared/importers/default_config_en.yml
  rasa/shared/importers/default_config_other_language.yml
  rasa/utils/tensorflow/environment.py
  tests/nlu/tokenizers/test_whitespace_tokenizer.py
Labels: status:ready-to-merge

#6683 implemented additional telemetry events
  docs/docs/telemetry/events.json
  rasa/cli/data.py
  rasa/cli/export.py
  rasa/cli/scaffold.py
  rasa/cli/shell.py
  rasa/cli/telemetry.py
  rasa/cli/x.py
  rasa/core/run.py
  rasa/core/test.py
  rasa/core/training/interactive.py
  rasa/core/visualize.py
  rasa/model.py
  rasa/nlu/test.py
  rasa/telemetry.py
  tests/core/test_evaluation.py
  tests/test_telemetry.py
  tests/test_test.py
Labels: status:ready-to-merge

#6373 Conversation Patterns Docs
  .typo-ci.yml
  CHANGELOG.mdx
  data/test_domains/restaurant_form.yml
  docs/docs/business-logic.mdx
  docs/docs/chitchat-faqs.mdx
  docs/docs/contextual-conversations.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/glossary.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/reminders-and-external-events.mdx
  docs/docs/unexpected-input.mdx
  docs/sidebars.js
  examples/formbot/domain.yml
  examples/reminderbot/actions/actions.py
  examples/reminderbot/config.yml
  examples/reminderbot/data/nlu.yml
  examples/reminderbot/domain.yml
  tests/core/test_examples.py
Labels: type:docs :book:

#6687 Update Rasa Playground content
  docs/docs/prototype-an-assistant.mdx
Labels: status:ready-to-merge

#6608 Best Practices for Stories
  docs/docs/rules.mdx
  docs/docs/writing-stories.mdx
Labels: status:ready-to-merge, type:docs :book:

#6701 Support list for the `slot_was_set` action
  data/test_stories/story_slot_different_types.md
  data/test_yaml_stories/story_slot_different_types.yml
  rasa/utils/schemas/stories.yml
  tests/core/training/converters/test_story_markdown_to_yaml_converter.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:

#6709 New docs: theme updates IV
  docs/docs/command-line-interface.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: status:ready-to-merge

#6713 Updated retrieval action docs with new prefix
  docs/docs/retrieval-actions.mdx
Labels: status:ready-to-merge

#6717 add telemetry prefix to docs commands
  docs/scripts/compile_program_outputs.js
Labels: status:ready-to-merge

#6720 Update playground rules section
  CODEOWNERS
  docs/docs/prototype-an-assistant.mdx
Labels: status:ready-to-merge

#6730 Update codeowners file
  CODEOWNERS
Labels: status:ready-to-merge

#6719 prepared release of version 1.10.13
  CHANGELOG.rst
  changelog/6577.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#6275 Pass message metadata to interpreter when parsing
  changelog/6275.feature.rst
  rasa/core/interpreter.py
  rasa/core/processor.py
  rasa/shared/nlu/interpreter.py
  tests/core/test_processor.py
Labels: status:ready-to-merge

#6743 Update URL of ConveRT
  changelog/6741.bugfix.md
  docs/docs/components.mdx
  rasa/nlu/tokenizers/convert_tokenizer.py
Labels: status:ready-to-merge

#6715 Docs: theme updates V
  CHANGELOG.mdx
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: status:ready-to-merge, type:docs :book:

#6740 Translate wrong rst changelog fragments to markdown
  changelog/5784.misc.md
  changelog/6055.improvement.md
  changelog/6275.feature.md
  changelog/6275.feature.rst
Labels: status:ready-to-merge

#6645 Add docs related to Rasa Action Server GH Action
  docs/docs/how-to-deploy.mdx
Labels: status:ready-to-merge

#6748 prepared release of version 1.10.14
  CHANGELOG.rst
  changelog/6741.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#6735 Updated tests (to investigate test_lock_store.py behavior)
  .github/workflows/continous-integration.yml
  changelog/6735.misc.md
  tests/cli/test_cli.py
  tests/core/test_lock_store.py
Labels: status:ready-to-merge

#6744 Fix docs theme versions
  docs/docusaurus.config.js
Labels: status:ready-to-merge

#6739 bump rasabaster version
  pyproject.toml
Labels: status:ready-to-merge

#6711 fix adding slot values to states
  changelog/6711.bugfix.md
  rasa/core/policies/memoization.py
  rasa/shared/core/domain.py
  tests/shared/core/test_domain.py
Labels: priority:critical, status:ready-to-merge, type:bug :bug:

#6273 Forward bot messages received from /tracker/events route to output channel
  changelog/6273.improvement.md
  docs/static/spec/rasa.yml
  rasa/core/processor.py
  rasa/server.py
  tests/core/test_processor.py
  tests/test_server.py
Labels: status:ready-to-merge

#6782 bump rasabaster
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#6731 make storyReader::read_from_file synchronous (#6641)
  docs/docs/training-data-importers.mdx
  rasa/core/training/converters/story_markdown_to_yaml_converter.py
  rasa/shared/core/training_data/loading.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
Labels: status:ready-to-merge

#6757 fill other slot if its entity mapping is unique
  changelog/6757.bugfix.md
  changelog/6757.improvement.md
  docs/docs/forms.mdx
  rasa/core/actions/forms.py
  rasa/shared/core/trackers.py
  tests/core/actions/test_forms.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#6751 Update docs for Retrieval Intents
  docs/docs/chitchat-faqs.mdx
  docs/docs/components.mdx
  docs/docs/retrieval-actions.mdx
  docs/docs/stories.mdx
  docs/docs/training-data-format.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6777 docusaurus should raise errors on broken links
  changelog/6323.improvement.md
  changelog/6354.feature.md
  changelog/6354.removal.md
  changelog/6466.improvement.md
  docs/docusaurus.config.js
Labels: status:ready-to-merge

#6699 Model regression tests - show last performance on master
  .github/templates/model_regression_test_results.tmpl
  .github/workflows/ci-model-regression.yml
Labels: status:ready-to-merge

#6723 Improve training data importers docs
  docs/docs/training-data-importers.mdx
Labels: type:docs :book:

#6772 Updated Unexpected Input Example to Form Bot
  docs/docs/unexpected-input.mdx
Labels: type:docs :book:

#6770 Updated Docs to Use Chat Component
  docs/docs/business-logic.mdx
  docs/docs/chitchat-faqs.mdx
  docs/docs/contextual-conversations.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/writing-stories.mdx
Labels: type:docs :book:

#6812 Ignore tests that use ConveRT for now
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/test_config.py
  tests/nlu/test_train.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
Labels: status:ready-to-merge

#6800 Updated dependencies before 2.0 release
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#6818 Support "Rules" in the YAMLStoryWriter
  data/test_yaml_stories/rules_with_stories_sorted.yaml
  rasa/shared/core/generator.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/story_step_builder.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/core/training_data/story_writer/yaml_story_writer.py
  rasa/shared/core/training_data/structures.py
  tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
Labels: area:rasa-oss :ferris_wheel:, status:ready-to-merge, type:bug :bug:

#6816 Fix typo
  docs/docs/chitchat-faqs.mdx
Labels: status:ready-to-merge

#6639 Consider confidence values in 'ensure_consistent_bilou_tagging'
  changelog/6039.improvment.md
  docs/docs/nlu-training-data.mdx
  docs/docs/training-data-format.mdx
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/extractors/crf_entity_extractor.py
  rasa/nlu/utils/bilou_utils.py
  tests/nlu/utils/test_bilou_utils.py
Labels: status:ready-to-merge

#6828 Skip ConveRT tests
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/test_config.py
  tests/nlu/test_interpreter.py
  tests/nlu/test_train.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
Labels: status:ready-to-merge

#6830 Fix prototyper link
  docs/docs/docker/building-in-docker.mdx
  docs/docs/installation.mdx
  tests/docs/test_docs_use_base_url.py
Labels: status:ready-to-merge

#6808 Mask DATASET and CONFIG variables in the Model Regression CI
  .github/templates/configuration_variables.tmpl
Labels: status:ready-to-merge

#6832 Detect wrong heading hierarchy in docs
  tests/docs/test_docs_header_hierarchy.py
Labels: status:ready-to-merge

#6829 Allow overriding of default intents
  rasa/shared/core/domain.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#6838 prepared release of version 2.0.0rc3
  pyproject.toml
  rasa/version.py
Labels: area:rasa-oss :ferris_wheel:, status:ready-to-merge

#6837 Remove ConveRT model from model regression tests
  .github/configs/mr-test-example.yaml
  .github/configs/mr-test-schedule.yaml
Labels: status:ready-to-merge

#6799 updated model persistor docs and aws persistor
  CHANGELOG.mdx
  changelog/5737.bugfix.md
  docs/docs/components.mdx
  docs/docs/installation.mdx
  docs/docs/jupyter-notebooks.mdx
  docs/docs/model-storage.mdx
  rasa/nlu/persistor.py
  tests/nlu/test_persistor.py
Labels: type:docs :book:

#6849 fix header level in model-storage.mdx
  docs/docs/model-storage.mdx
Labels: status:ready-to-merge

#6846 validate docs snippets against all schemas
  docs/docs/contextual-conversations.mdx
  docs/docs/fallback-handoff.mdx
  docs/docs/stories.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docs/training-data-format.mdx
  tests/docs/test_docs_training_data.py
Labels: status:ready-to-merge

#6848 Improve e2e testing docs in testing-your-assistant.mdx
  docs/docs/testing-your-assistant.mdx
Labels: status:ready-to-merge, type:docs :book:

#6824 Docs Subsection on Using Multiple Domain Files
  docs/docs/domain.mdx
Labels: type:docs :book:

#6823 Update markdown example to yml
  changelog/6823.doc.md
  docs/static/spec/rasa.yml
Labels: area:rasa-oss :ferris_wheel:, status:ready-to-merge, type:docs :book:
