Repository RasaHQ/rasa, pull requests merged in 2020-11, with the labels that each got.

#7139 remove max-parallel from workflow
  .github/workflows/continous-integration.yml
Labels: status:ready-to-merge

#7114 Modifications to telemetry initialization
  rasa/__main__.py
  rasa/telemetry.py
Labels: status:ready-to-merge

#7121 small docs updates
  docs/docs/command-line-interface.mdx
  docs/docs/generating-nlu-data.mdx
  docs/docs/installation.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#7161 add workflow to periodically cancel stale workflows
  .github/workflows/cancel-stale-workflows.yml
Labels: status:ready-to-merge

#7162 Docs edits alan 202010 backport
  docs/docs/command-line-interface.mdx
  docs/docs/generating-nlu-data.mdx
  docs/docs/installation.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#7164 Update legacy docs link to be rel="nofollow noreferrer noopener"
  docs/docusaurus.config.js
Labels: status:ready-to-merge

#7099 Style Guide Updates to Training-Data-Format Docs
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge, type:docs :book:

#6738 Updates to the domain docs as a result of docs workshop
  docs/docs/domain.mdx
Labels: status:ready-to-merge, type:docs :book:

#7170 Kafka broker docs
  docs/docs/event-brokers.mdx
Labels: status:ready-to-merge

#7157 pydocstyle only new changes
  Makefile
Labels: status:ready-to-merge

#7172 merge 2.0.x to master
  Makefile
  docs/docs/components.mdx
  docs/docs/event-brokers.mdx
  docs/docs/training-data-format.mdx
  rasa/__main__.py
  rasa/telemetry.py
Labels: status:ready-to-merge

#7141 Fix failure of rasa x CLI command if git is not installed
  changelog/7140.bugfix.md
  rasa/cli/x.py
Labels: status:ready-to-merge

#6500 Added configurable prefixes for Redis Tracker and Lock stores
  changelog/6498.improvement.md
  data/test_endpoints/example_endpoints.yml
  docs/docs/lock-stores.mdx
  docs/docs/tracker-stores.mdx
  rasa/core/lock_store.py
  rasa/core/tracker_store.py
  tests/core/test_lock_store.py
  tests/core/test_tracker_stores.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#7184 update yarn.lock for security patches
  docs/yarn.lock
Labels: status:ready-to-merge

#7132 Adapt the training data reader and emulator for LUIS to their latest format
  changelog/7132.improvement.md
  data/examples/luis/demo-restaurants_v2.json
  data/examples/luis/demo-restaurants_v4.json
  data/examples/luis/demo-restaurants_v7.json
  data/test/luis_converted_to_rasa.json
  data/test/wit_converted_to_rasa.json
  docs/docs/migrate-from/luis_export.png
  docs/docs/migrate-from/microsoft-luis-to-rasa.mdx
  rasa/nlu/emulators/luis.py
  rasa/shared/nlu/training_data/formats/luis.py
  tests/nlu/emulators/test_luis.py
  tests/nlu/emulators/test_no_emulator.py
  tests/shared/nlu/training_data/test_training_data.py
  tests/shared/test_data.py
Labels: status:ready-to-merge

#6992 added id to svg element in visualization.html
  rasa/shared/core/training_data/visualization.html
Labels: status:ready-to-merge

#7134 warn for invalid keys for components
  changelog/6966.improvement.md
  rasa/nlu/components.py
  rasa/nlu/model.py
  tests/nlu/test_components.py
Labels: status:ready-to-merge

#7171 optional slot mappings
  changelog/7068.improvement.md
  docs/docs/default-actions.mdx
  docs/docs/migration-guide.mdx
  rasa/core/actions/action.py
  rasa/core/actions/forms.py
  rasa/core/actions/two_stage_fallback.py
  rasa/core/training/interactive.py
  rasa/shared/core/domain.py
  rasa/shared/importers/importer.py
  tests/core/actions/test_forms.py
  tests/core/test_actions.py
  tests/core/test_featurizer.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#7040 make converter convert numbers as entity type
  changelog/7031.bugfix.md
  rasa/shared/nlu/training_data/schemas/data_schema.py
  tests/shared/utils/test_validation.py
Labels: status:ready-to-merge

#7186 slack connector: implemented signing secret and updated docs
  changelog/7186.bugfix.md
  docs/docs/connectors/img/slack-create-app.png
  docs/docs/connectors/img/slack-events.png
  docs/docs/connectors/img/slack-install-app.png
  docs/docs/connectors/img/slack-interactivity.png
  docs/docs/connectors/img/slack-request-url.png
  docs/docs/connectors/img/slack-scopes.png
  docs/docs/connectors/img/slack-secret.png
  docs/docs/connectors/slack.mdx
  rasa/core/channels/slack.py
  rasa/shared/constants.py
  rasa/shared/core/training_data/story_reader/markdown_story_reader.py
  tests/core/channels/test_slack.py
  tests/core/test_channels.py
Labels: status:ready-to-merge

#6746 Updated Rasa example bots for 2.0
  examples/concertbot/data/nlu.yml
  examples/concertbot/data/rules.yml
  examples/concertbot/data/stories.yml
  examples/formbot/data/rules.yml
  examples/formbot/domain.yml
  examples/formbot/tests/test_stories.yml
  examples/knowledgebasebot/data/nlu.yml
  examples/knowledgebasebot/data/rules.yml
  examples/knowledgebasebot/data/stories.yml
  examples/reminderbot/data/stories.yml
  examples/rules/data/rules.yml
Labels: status:ready-to-merge

#7200 Fix `all_retrieval_intents` key in response selector output
  changelog/7200.bugfix.md
  rasa/nlu/selectors/response_selector.py
  tests/nlu/selectors/test_selectors.py
Labels: status:ready-to-merge

#7208 Update the setup-poetry GH action to v4
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
Labels: status:ready-to-merge

#7203 ignore `FallbackClassifier` predictions during evaluation
  changelog/6285.improvement.md
  rasa/nlu/classifiers/fallback_classifier.py
  rasa/nlu/test.py
  tests/nlu/classifiers/test_fallback_classifier.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#7213 Run the gitleaks scan only on a pull request event
  .github/workflows/security-scans.yml
Labels: status:ready-to-merge

#7215 prepared release of version 2.0.5
  CHANGELOG.mdx
  changelog/7200.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7027 Remove library specific tokenizers #108
  changelog/7027.improvement.md
  docs/docs/components.mdx
  docs/docs/migration-guide.mdx
  rasa/nlu/constants.py
  rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py
  rasa/nlu/tokenizers/convert_tokenizer.py
  rasa/nlu/tokenizers/lm_tokenizer.py
  rasa/nlu/utils/hugging_face/hf_transformers.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/featurizers/test_lm_featurizer.py
  tests/nlu/test_config.py
  tests/nlu/test_train.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
  tests/nlu/tokenizers/test_lm_tokenizer.py
  tests/nlu/utils/test_hf_transformers.py
Labels: status:ready-to-merge

#7136 Policy Predictions for End-to-End
  changelog/7136.feature.md
  changelog/7136.removal.md
  rasa/core/agent.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/fallback.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/mapping_policy.py
  rasa/core/policies/memoization.py
  rasa/core/policies/policy.py
  rasa/core/policies/rule_policy.py
  rasa/core/policies/sklearn_policy.py
  rasa/core/policies/ted_policy.py
  rasa/core/policies/two_stage_fallback.py
  rasa/core/processor.py
  rasa/core/test.py
  rasa/server.py
  rasa/shared/core/constants.py
  rasa/shared/core/trackers.py
  tests/core/policies/test_rule_policy.py
  tests/core/test_actions.py
  tests/core/test_ensemble.py
  tests/core/test_policies.py
  tests/core/test_processor.py
  tests/test_server.py
Labels: status:ready-to-merge

#7222 Merge 2.0.x
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  CHANGELOG.mdx
  changelog/7140.bugfix.md
  changelog/7186.bugfix.md
  examples/concertbot/data/nlu.yml
  examples/concertbot/data/rules.yml
  examples/concertbot/data/stories.yml
  examples/formbot/data/rules.yml
  examples/formbot/domain.yml
  examples/formbot/tests/test_stories.yml
  examples/knowledgebasebot/data/nlu.yml
  examples/knowledgebasebot/data/rules.yml
  examples/knowledgebasebot/data/stories.yml
  examples/reminderbot/data/stories.yml
  examples/rules/data/rules.yml
  pyproject.toml
  rasa/nlu/selectors/response_selector.py
  rasa/version.py
  tests/nlu/selectors/test_selectors.py
Labels: status:ready-to-merge

#7223 backport fix for multiple sanic workers
  changelog/6629.bugfix.md
  rasa/core/utils.py
  tests/core/test_utils.py
Labels: status:ready-to-merge

#7220 Two stage fallback fix
  changelog/7176.bugfix.md
  rasa/core/actions/two_stage_fallback.py
  rasa/shared/core/trackers.py
  tests/core/actions/test_two_stage_fallback.py
Labels: status:ready-to-merge

#7229 prepared release of version 2.0.6
  CHANGELOG.mdx
  changelog/6629.bugfix.md
  changelog/7176.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7199 bump docs theme to 0.8.3
  docs/package.json
  docs/yarn.lock
Labels: status:ready-to-merge

#7239 Update the setup-gcloud GH action
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
Labels: status:ready-to-merge

#7183 Response converter
  changelog/6865.improvement.md
  docs/docs/migration-guide.mdx
  rasa/cli/arguments/data.py
  rasa/cli/data.py
  rasa/core/training/converters/responses_prefix_converter.py
  rasa/nlu/training_data/converters/nlg_markdown_to_yaml_converter.py
  rasa/shared/core/domain.py
  rasa/shared/core/training_data/story_reader/story_reader.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/data.py
  tests/cli/test_rasa_data.py
  tests/nlu/training_data/converters/test_nlg_markdown_to_yaml_converter.py
  tests/shared/core/test_domain.py
Labels: status:ready-to-merge

#7236 merge 2.0.x to master
  CHANGELOG.mdx
  changelog/6629.bugfix.md
  pyproject.toml
  rasa/core/actions/two_stage_fallback.py
  rasa/core/channels/slack.py
  rasa/shared/core/trackers.py
  rasa/version.py
  tests/core/actions/test_two_stage_fallback.py
Labels: status:ready-to-merge

#7242 fix docstyle validations
  .github/workflows/continous-integration.yml
  Makefile
Labels: status:ready-to-merge

#7241 Add docs for the pipe symbol in YAML
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#7219 Pika multiprocessing fix for 1.10.x
  .github/workflows/continous-integration.yml
  changelog/7219.bugfix.rst
  rasa/core/brokers/pika.py
  tests/core/test_broker.py
Labels: status:ready-to-merge

#7225 Trigger session start action as follow up to restart action
  .github/workflows/continous-integration.yml
  changelog/5974.bugfix.md
  rasa/shared/core/events.py
  tests/core/test_processor.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#7264 prepared release of version 1.10.17
  CHANGELOG.rst
  changelog/7219.bugfix.rst
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7246 Fixed changing fingerprints even though training data did not change
  changelog/7246.bugfix.md
  rasa/core/utils.py
  rasa/model.py
  rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
  rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py
  rasa/nlu/utils/hugging_face/hf_transformers.py
  rasa/shared/core/domain.py
  rasa/shared/core/training_data/structures.py
  rasa/shared/nlu/training_data/message.py
  rasa/shared/nlu/training_data/training_data.py
  rasa/shared/utils/io.py
  tests/shared/nlu/training_data/test_message.py
  tests/shared/nlu/training_data/test_training_data.py
  tests/utils/test_io.py
Labels: status:ready-to-merge

#7233 update documentation for custom slot mappings
  docs/docs/forms.mdx
Labels: status:ready-to-merge

#7278 set nlu fallback confidence to 1 - intent confidence
  changelog/7278.improvement.md
  docs/docs/components.mdx
  rasa/nlu/classifiers/fallback_classifier.py
  tests/nlu/classifiers/test_fallback_classifier.py
Labels: status:ready-to-merge

#7288 Add default values for `text` and `bool` slots if referenced by name
  changelog/7253.bugfix.md
  docs/docs/domain.mdx
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#7293 merge 2.0.x master
  .github/workflows/continous-integration.yml
  changelog/5974.bugfix.md
  rasa/shared/core/events.py
  tests/core/test_processor.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#7098 make rasa test support retrieval intents for test stories
  changelog/7002.bugfix.md
  data/test_yaml_stories/non_test_full_retrieval_intent_story.yml
  data/test_yaml_stories/test_base_retrieval_intent_story.yml
  data/test_yaml_stories/test_base_retrieval_intent_wrong_prediction.yml
  data/test_yaml_stories/test_full_retrieval_intent_story.yml
  data/test_yaml_stories/test_full_retrieval_intent_wrong_prediction.yml
  rasa/core/featurizers/tracker_featurizers.py
  rasa/core/test.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/nlu/constants.py
  tests/core/conftest.py
  tests/core/test_evaluation.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#7297 Prepare release 2.1.0
  CHANGELOG.mdx
  changelog/4341.improvement.md
  changelog/5715.improvement.md
  changelog/5974.bugfix.md
  changelog/6285.improvement.md
  changelog/6470.misc.md
  changelog/6474.improvement.md
  changelog/6498.improvement.md
  changelog/6571.improvement.md
  changelog/6582.bugfix.md
  changelog/6721.bugfix.md
  changelog/6760.bugfix.md
  changelog/6852.improvement.md
  changelog/6860.improvement.md
  changelog/6865.improvement.md
  changelog/6966.improvement.md
  changelog/6973.bugfix.md
  changelog/6973.doc.md
  changelog/6977.improvement.md
  changelog/6986.bugfix.md
  changelog/7001.bugfix.md
  changelog/7002.bugfix.md
  changelog/7015.misc.md
  changelog/7027.improvement.md
  changelog/7031.bugfix.md
  changelog/7034.bugfix.md
  changelog/7061.improvement.md
  changelog/7068.improvement.md
  changelog/7090.misc.md
  changelog/7102.improvement.md
  changelog/7122.improvement.md
  changelog/7132.improvement.md
  changelog/7136.feature.md
  changelog/7136.removal.md
  changelog/7160.improvement.md
  changelog/7204.bugfix.md
  changelog/7246.bugfix.md
  changelog/7253.bugfix.md
  changelog/7263.improvement.md
  changelog/7263.removal.md
  changelog/7278.improvement.md
  poetry.lock
  pyproject.toml
  rasa/constants.py
  rasa/core/tracker_store.py
  rasa/nlu/config.py
  rasa/version.py
Labels: status:ready-to-merge

#7308 Fix `black` to be the same version in the pre-commit config as it's in the pyproject config
  .pre-commit-config.yaml
Labels: area:rasa-oss/infrastructure :bullettrain_front:, type:maintenance :wrench:

#7323 use ref instead of branch name
  .github/workflows/continous-integration.yml
Labels: status:ready-to-merge

#7317 Simplify is_url function
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/vulnerability-scan.yml
  changelog/7317.bugfix.md
  rasa/core/run.py
  rasa/nlu/utils/__init__.py
  tests/nlu/test_utils.py
Labels: status:ready-to-merge

#7316 core featurizers should use regex interpreter if core was trained separately
  changelog/7316.bugfix.md
  rasa/core/featurizers/single_state_featurizer.py
  rasa/core/featurizers/tracker_featurizers.py
  tests/core/test_featurizer.py
Labels: status:ready-to-merge, type:bug :bug:

#7356 prepared release of version 2.0.7
  CHANGELOG.mdx
  changelog/5974.bugfix.md
  changelog/7316.bugfix.md
  changelog/7317.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7351 merge 2.1.1 to master
  CHANGELOG.mdx
  pyproject.toml
  rasa/shared/core/trackers.py
  rasa/version.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge

#7354 Minor Language Tweak for Memoization Policy
  docs/docs/policies.mdx
Labels: status:ready-to-merge

#7367 Remove the set-env command - 1.10.x
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/vulnerability-scan.yml
Labels: status:ready-to-merge

#7369 Don't start with an Empty config.yml
  rasa/cli/initial_project/config.yml
Labels: status:ready-to-merge

#7353 Add TED link for Youtube.
  docs/docs/policies.mdx
Labels: status:ready-to-merge

#7235 fix conversation starts with slots initial value
  changelog/7235.bugfix.md
  rasa/core/policies/rule_policy.py
  tests/core/policies/test_rule_policy.py
Labels: priority:critical, status:ready-to-merge, type:bug :bug:

#7381 Prepare release 1.10.18
  CHANGELOG.rst
  changelog/7340.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7315 Add the possibility to extract data from the domain in components
  rasa/nlu/classifiers/mitie_intent_classifier.py
  rasa/nlu/classifiers/sklearn_intent_classifier.py
  rasa/nlu/components.py
  rasa/nlu/extractors/duckling_entity_extractor.py
  rasa/nlu/extractors/entity_synonyms.py
  rasa/nlu/extractors/mitie_entity_extractor.py
  rasa/nlu/extractors/regex_entity_extractor.py
  rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py
  rasa/nlu/model.py
  rasa/nlu/registry.py
  rasa/nlu/utils/mitie_utils.py
  rasa/nlu/utils/pattern_utils.py
  rasa/nlu/utils/spacy_utils.py
  tests/nlu/extractors/test_entity_synonyms.py
  tests/nlu/utils/test_pattern_utils.py
Labels: status:ready-to-merge

#7398 Bring 2.0.x RulePolicy bug fixes into 2.1.x
  changelog/7235.bugfix.md
  rasa/core/policies/rule_policy.py
  tests/core/policies/test_rule_policy.py
Labels: area:rasa-oss :ferris_wheel:, type:bug :bug:

#7334 Fix incorrect attribute for key prefix in RedisTrackerStore
  changelog/7306.bugfix.md
  rasa/core/tracker_store.py
  tests/shared/core/test_trackers.py
Labels: status:ready-to-merge
