Repository RasaHQ/rasa, pull requests merged in 2020-08, with the labels that each got.

#6242 Windows support and testing
  .github/workflows/continous-integration.yml
  Makefile
  changelog/5784.misc.rst
  poetry.lock
  pyproject.toml
  pytest.ini
  rasa/cli/data.py
  rasa/cli/export.py
  rasa/core/__init__.py
  rasa/core/channels/hangouts.py
  rasa/core/channels/mattermost.py
  rasa/core/channels/slack.py
  rasa/core/test.py
  rasa/core/training/loading.py
  rasa/importers/autoconfig.py
  rasa/nlu/training_data/util.py
  rasa/nlu/utils/__init__.py
  rasa/test.py
  tests/cli/test_cli.py
  tests/cli/test_rasa_export.py
  tests/cli/test_rasa_init.py
  tests/conftest.py
  tests/core/channels/test_cmdline.py
  tests/core/test_agent.py
  tests/core/test_channels.py
  tests/core/test_data.py
  tests/core/test_ensemble.py
  tests/core/test_evaluation.py
  tests/core/test_examples.py
  tests/core/test_story_conflict.py
  tests/core/test_tracker_stores.py
  tests/core/utilities.py
  tests/importers/test_autoconfig.py
  tests/importers/test_multi_project.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/featurizers/test_convert_featurizer.py
  tests/nlu/test_config.py
  tests/nlu/test_train.py
  tests/nlu/test_utils.py
  tests/nlu/tokenizers/test_convert_tokenizer.py
  tests/nlu/tokenizers/test_lm_tokenizer.py
  tests/nlu/training_data/test_entities_parser.py
  tests/test_server.py
  tests/test_validator.py
  tests/utilities.py
  tests/utils/test_endpoints.py
Labels: status:ready-to-merge

#6318 note on testing custom actions
  docs/docs/testing-your-assistant.mdx
Labels: status:ready-to-merge

#6311 Bug Fix for Slack Metadata Param
  rasa/core/channels/slack.py
Labels: status:ready-to-merge

#6321 fix folder for documentation workflow
  .github/workflows/documentation.yml
Labels: status:ready-to-merge

#6327 update README instructions for new docs system
  README.md
Labels: status:ready-to-merge

#6325 useBaseUrl() hook for redoc
  docs/docs/api/action-server.mdx
  docs/docs/api/http-api.mdx
  docs/package.json
  docs/src/components/redoc.jsx
  docs/yarn.lock
Labels: status:ready-to-merge

#6235 Port formbot to rules/yaml format
  examples/formbot/config.yml
  examples/formbot/data/nlu.md
  examples/formbot/data/nlu.yml
  examples/formbot/data/rules.yml
  examples/formbot/data/stories.md
  examples/formbot/data/stories.yml
Labels: status:ready-to-merge

#6333 prepared release of version 1.10.10
  CHANGELOG.rst
  changelog/6280.rst
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#6331 Add alpha release hint to prototyper page
  docs/docs/user-guide/prototype-an-assistant.mdx
Labels: status:ready-to-merge

#6351 Revert "Port formbot to rules/yaml format"
  examples/formbot/config.yml
  examples/formbot/data/nlu.md
  examples/formbot/data/nlu.yml
  examples/formbot/data/rules.yml
  examples/formbot/data/stories.md
  examples/formbot/data/stories.yml
Labels: status:ready-to-merge

#6312 rename 'form' event to 'active_loop'
  data/test_yaml_stories/rules_without_stories.yml
  data/test_yaml_stories/stories_and_rules.yml
  docs/docs/user-guide/prototype-an-assistant.mdx
  examples/rules/data/rules.yml
  rasa/core/training/story_reader/yaml_story_reader.py
Labels: status:ready-to-merge

#6346 Fix chat caret issues with the prototyper in FF
  docs/static/js/rasa-chatblock.min.js
Labels: area:rasa-x/ui :sparkles:, status:ready-to-merge, type:docs :book:

#6344 RulePolicy: replace dots with conditions and co
  data/test_yaml_stories/rules_without_stories.yml
  data/test_yaml_stories/stories_and_rules.yml
  examples/concertbot/data/rules.yaml
  examples/knowledgebasebot/data/rules.yaml
  examples/reminderbot/data/rules.yml
  examples/rules/data/rules.yml
  rasa/core/training/story_reader/yaml_story_reader.py
  tests/core/training/story_reader/test_yaml_story_reader.py
Labels: status:ready-to-merge

#6195 rule policy documentation
  changelog/6065.feature.md
  changelog/6088.feature.md
  docs/docs/core/actions.mdx
  docs/docs/core/fallback-actions.mdx
  docs/docs/core/forms.mdx
  docs/docs/core/policies.mdx
  docs/docs/core/reminders-and-external-events.mdx
  docs/docs/core/retrieval-actions.mdx
  docs/docs/core/rules.mdx
  docs/docs/core/stories.mdx
  docs/docs/dialogue-elements/completing-tasks.mdx
  docs/docs/glossary.mdx
  docs/docs/migration-guide.mdx
  docs/docs/nlu/components.mdx
  docs/sidebars.js
  rasa/constants.py
  rasa/core/policies/ensemble.py
  rasa/core/training/story_reader/yaml_story_reader.py
Labels: status:ready-to-merge

#6345 predict core fallback if no rule found
  examples/rules/config.yml
  rasa/core/constants.py
  rasa/core/policies/ensemble.py
  rasa/core/policies/fallback.py
  rasa/core/policies/rule_policy.py
  tests/core/policies/test_rule_policy.py
  tests/core/test_agent.py
Labels: status:ready-to-merge

#6309 Documentation for Suggested Config feature
  data/configs_for_docs/example_for_suggested_config.yml
  data/configs_for_docs/example_for_suggested_config_after_train.yml
  docs/docs/api/model-configuration.mdx
  docs/docs/core/policies.mdx
  docs/docs/nlu/choosing-a-pipeline.mdx
  docs/docs/user-guide/prototype-an-assistant.mdx
  docs/docs/user-guide/rasa-tutorial.mdx
  docs/sidebars.js
  rasa/nlu/components.py
  tests/nlu/test_config.py
Labels: status:ready-to-merge

#6329 Rasa init to 20
  data/test_config/config_empty_after_dumping.yml
  data/test_config/config_with_comments_after_dumping.yml
  rasa/cli/initial_project/data/nlu.md
  rasa/cli/initial_project/data/nlu.yml
  rasa/cli/initial_project/data/rules.yml
  rasa/cli/initial_project/data/stories.md
  rasa/cli/initial_project/data/stories.yml
  rasa/importers/default_config.yml
  tests/cli/test_rasa_data.py
  tests/cli/test_rasa_init.py
  tests/cli/test_rasa_test.py
  tests/cli/test_rasa_train.py
  tests/core/test_data.py
  tests/importers/test_rasa.py
Labels: status:ready-to-merge

#6355 add `ambiguity_threshold` param to `FallbackClassifier`
  rasa/core/actions/action.py
  rasa/core/domain.py
  rasa/core/events/__init__.py
  rasa/core/interpreter.py
  rasa/core/policies/mapping_policy.py
  rasa/core/policies/two_stage_fallback.py
  rasa/core/processor.py
  rasa/core/tracker_store.py
  rasa/core/training/interactive.py
  rasa/core/training/story_reader/markdown_story_reader.py
  rasa/core/training/story_reader/yaml_story_reader.py
  rasa/nlu/classifiers/fallback_classifier.py
  rasa/nlu/constants.py
  rasa/nlu/emulators/dialogflow.py
  rasa/nlu/model.py
  rasa/nlu/test.py
  tests/core/test_interpreter.py
  tests/core/test_policies.py
  tests/core/test_processor.py
  tests/core/training/story_reader/test_common_story_reader.py
  tests/core/utilities.py
  tests/nlu/classifiers/test_fallback_classifier.py
  tests/test_server.py
Labels: status:ready-to-merge

#6305 Cdd docs
  .typo-ci.yml
  docs/docs/conversation-driven-development.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#6377 use autogenerated anchors instead of explicit ones
  CHANGELOG.mdx
  docs/docs/business-logic.mdx
  docs/docs/chitchat-faqs.mdx
  docs/docs/command-line-interface.mdx
  docs/docs/components/entity-extractors.mdx
  docs/docs/components/featurizers.mdx
  docs/docs/components/intent-classifiers.mdx
  docs/docs/components/language-models.mdx
  docs/docs/components/selectors.mdx
  docs/docs/components/tokenizers.mdx
  docs/docs/connectors/hangouts.mdx
  docs/docs/connectors/your-own-website.mdx
  docs/docs/contextual-conversations.mdx
  docs/docs/custom-actions.mdx
  docs/docs/docker/deploying-in-docker-compose.mdx
  docs/docs/event-brokers.mdx
  docs/docs/migration-guide.mdx
  docs/docs/nlg.mdx
  docs/docs/reminders-and-external-events.mdx
  docs/docs/retrieval-actions.mdx
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/stories.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docs/tracker-stores.mdx
  docs/docs/training-data-format.mdx
  docs/docs/tuning-your-model.mdx
Labels: status:ready-to-merge

#6368 Do not deepcopy domain slots
  changelog/6044.improvement.rst
  rasa/core/trackers.py
  tests/core/test_trackers.py
Labels: status:ready-to-merge

#6391 fix relative attention
  rasa/utils/tensorflow/transformer.py
  tests/core/test_policies.py
Labels: status:ready-to-merge

#6256 Added a schema and a writer for the 2.0 NLU Parser
  docs/conf.py
  rasa/core/events/__init__.py
  rasa/core/test.py
  rasa/core/training/interactive.py
  rasa/core/utils.py
  rasa/nlu/schemas/nlu.yml
  rasa/nlu/training_data/formats/markdown.py
  rasa/nlu/training_data/formats/rasa_yaml.py
  rasa/nlu/training_data/formats/readerwriter.py
  rasa/nlu/training_data/training_data.py
  rasa/utils/io.py
  tests/cli/conftest.py
  tests/cli/test_rasa_test.py
  tests/cli/test_rasa_train.py
  tests/cli/test_rasa_x.py
  tests/conftest.py
  tests/core/test_exporter.py
  tests/core/test_interactive.py
  tests/importers/test_importer.py
  tests/nlu/training_data/formats/test_rasa_yaml.py
  tests/test_validator.py
  tests/utilities.py
  tests/utils/test_io.py
Labels: status:ready-to-merge

#6384 rule policy improvements
  docs/docs/forms.mdx
  examples/rules/data/nlu.yml
  examples/rules/data/rules.yml
  examples/rules/domain.yml
  rasa/core/actions/forms.py
  rasa/core/constants.py
  rasa/core/domain.py
  rasa/core/processor.py
  tests/core/actions/test_forms.py
  tests/core/test_agent.py
  tests/core/test_domain.py
  tests/core/test_processor.py
  tests/importers/test_rasa.py
Labels: status:ready-to-merge

#6388 add links for legacy docs versions
  docs/docs/index.mdx
  docs/docusaurus.config.js
Labels: status:ready-to-merge

#6396 Added a schema and a writer for the 2.0 Core training data
  changelog/6374.feature.md
  data/test_mixed_yaml_md_stories/stories_part_1.yml
  data/test_multifile_yaml_stories/stories_part_1.yml
  data/test_yaml_stories/rules_without_stories.yml
  data/test_yaml_stories/simple_story_with_only_end.yml
  data/test_yaml_stories/stories.yml
  data/test_yaml_stories/stories_and_rules.yml
  data/test_yaml_stories/stories_defaultdomain.yml
  data/test_yaml_stories/stories_unused_checkpoints.yml
  data/test_yaml_stories/story_with_slot_was_set.yml
  examples/rules/data/rules.yml
  rasa/core/schemas/stories.yml
  rasa/core/training/story_reader/markdown_story_reader.py
  rasa/core/training/story_reader/story_reader.py
  rasa/core/training/story_reader/story_step_builder.py
  rasa/core/training/story_reader/yaml_story_reader.py
  rasa/core/training/story_writer/yaml_story_writer.py
  rasa/core/training/structures.py
  tests/core/training/story_reader/test_yaml_story_reader.py
  tests/core/training/story_writer/test_yaml_story_writer.py
Labels: status:ready-to-merge

#6375 Skip the model regression tests if a configuration doesn't exist
  .github/runner/github-runner-deployment.yaml.tmpl
  .github/workflows/ci-model-regression.yml
Labels: status:ready-to-merge

#6405 improved getting started docs
  .typo-ci.yml
  docs/docs/http-api.mdx
  docs/docs/index.mdx
  docs/docs/installation.mdx
  docs/docs/messaging-and-voice-channels.mdx
  docs/docs/model-storage.mdx
  docs/docs/nlg.mdx
  docs/docs/prototype-an-assistant.mdx
  docs/docs/testing-your-assistant.mdx
Labels: status:ready-to-merge

#6412 Prototyper updates for 2.0.0a2
  docs/docs/prototype-an-assistant.mdx
  docs/docs/rules.mdx
Labels: status:ready-to-merge

#6413 Training data format update
  docs/docs/nlu-training-data.mdx
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#6315 2.0 NLU Best Practices Doc
  docs/docs/generating-nlu-data.mdx
Labels: status:ready-to-merge

#6343 Generate the source code reference
  .gitignore
  docs/package.json
  docs/pydoc-markdown.yml
  docs/sidebars.js
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#6416 update writing stories docs page and IL content
  docs/docs/forms.mdx
  docs/docs/glossary.mdx
  docs/docs/stories.mdx
  docs/docs/unexpected-input.mdx
  docs/docs/writing-stories.mdx
Labels: status:ready-to-merge

#6386 Escalate lockstore errors
  changelog/6226.improvement.rst
  docs/api/lock-stores.rst
  rasa/core/lock_store.py
  tests/core/test_lock_store.py
Labels: status:ready-to-merge

#6418 form rename to active_loop
  docs/docs/fallback-handoff.mdx
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
  docs/docs/prototype-an-assistant.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#6323 Response generator responses with multimedia elements
  changelog/6323.improvement.md
  docs/docs/chitchat-faqs.mdx
  docs/docs/retrieval-actions.mdx
  examples/moodbot/config.yml
  examples/moodbot/data/nlu.md
  examples/moodbot/data/nlu.yml
  examples/moodbot/data/rules.yml
  examples/moodbot/data/stories.md
  examples/moodbot/data/stories.yml
  rasa/core/actions/action.py
  rasa/core/training/interactive.py
  rasa/core/training/loading.py
  rasa/core/training/story_reader/markdown_story_reader.py
  rasa/data.py
  rasa/importers/utils.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/schemas/nlu.yml
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/training_data/formats/markdown_nlg.py
  rasa/nlu/training_data/formats/rasa_yaml.py
  rasa/nlu/training_data/loading.py
  rasa/nlu/training_data/lookup_tables_parser.py
  rasa/nlu/training_data/training_data.py
  rasa/server.py
  tests/cli/test_rasa_interactive.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/test_actions.py
  tests/core/test_agent.py
  tests/core/test_broker.py
  tests/core/test_data.py
  tests/core/test_exporter.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_evaluation.py
  tests/nlu/training_data/formats/test_rasa_yaml.py
  tests/nlu/training_data/test_markdown_nlg.py
  tests/nlu/training_data/test_training_data.py
  tests/test_server.py
  tests/test_train.py
  tests/test_validator.py
  tests/utils/test_validation.py
Labels: status:ready-to-merge

#6429 merge 1.10.x to master
  CHANGELOG.mdx
  changelog/6044.improvement.md
  changelog/6226.improvement.md
  docs/docs/lock-stores.mdx
  poetry.lock
  rasa/core/actions/action.py
  rasa/core/domain.py
  rasa/core/lock_store.py
  rasa/core/trackers.py
  tests/core/test_domain.py
  tests/core/test_lock_store.py
  tests/core/test_trackers.py
Labels: status:ready-to-merge

#6428 Fix autodoc
  .github/workflows/documentation.yml
Labels: status:ready-to-merge

#6434 Added test that checks example bots' training data
  examples/concertbot/data/nlu.yaml
  examples/concertbot/data/rules.yaml
  examples/concertbot/data/stories.yaml
  examples/concertbot/domain.yml
  examples/knowledgebasebot/data/nlu.yaml
  examples/knowledgebasebot/data/rules.yaml
  examples/knowledgebasebot/domain.yml
  examples/moodbot/data/nlu.yml
  examples/moodbot/data/rules.yml
  examples/moodbot/data/stories.yml
  examples/moodbot/domain.yml
  examples/reminderbot/data/nlu.yml
  examples/reminderbot/data/rules.yml
  examples/reminderbot/domain.yml
  rasa/core/schemas/stories.yml
  tests/examples/test_example_bots_training_data.py
Labels: status:ready-to-merge

#6436 Docs issues aren't marked as stale
  .github/stale.yml
Labels: status:ready-to-merge

#6438 fix slot syntax in docs
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
  docs/docs/rules.mdx
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#5850 let buttons template accept string replacement from existing slot-values
  changelog/5850.bugfix.md
  rasa/core/nlg/interpolator.py
  rasa/core/nlg/template.py
  tests/core/test_nlg.py
Labels: status:ready-to-merge

#6359 Remove np.array
  changelog/6282.bugfix.md
  rasa/nlu/classifiers/diet_classifier.py
  rasa/utils/tensorflow/model_data.py
Labels: area:rasa-oss :ferris_wheel:

#6441 typo fixes
  .typo-ci.yml
  docs/docs/training-data-format.mdx
Labels: status:ready-to-merge

#6443 fix GH release creation for prerelease versions
  .github/workflows/continous-integration.yml
  scripts/publish_gh_release_notes.py
Labels: status:ready-to-merge

#6446 Cleanup merge issues doc
  docs/conf.py
  docs/docusaurus.config.js
  docs/makefile
  docs/src/pages/styles.module.css
Labels: status:ready-to-merge

#6451 Fixed training data for the initial project
  rasa/cli/initial_project/data/nlu.yml
  rasa/cli/initial_project/data/rules.yml
  rasa/cli/initial_project/data/stories.yml
  rasa/cli/initial_project/domain.yml
  tests/examples/test_example_bots_training_data.py
Labels: status:ready-to-merge

#6352 form bot fixes
  examples/formbot/config.yml
  examples/formbot/data/nlu.md
  examples/formbot/data/nlu.yml
  examples/formbot/data/rules.yml
  examples/formbot/data/stories.md
  examples/formbot/data/stories.yml
  tests/core/conftest.py
  tests/core/test_examples.py
  tests/test_server.py
Labels: status:ready-to-merge

#6449 Docs lint/test traning data
  .github/workflows/continous-integration.yml
  CHANGELOG.mdx
  Makefile
  docs/docs/chitchat-faqs.mdx
  docs/docs/components/custom-nlu-components.mdx
  docs/docs/components/entity-extractors.mdx
  docs/docs/components/featurizers.mdx
  docs/docs/components/intent-classifiers.mdx
  docs/docs/components/language-models.mdx
  docs/docs/components/tokenizers.mdx
  docs/docs/connectors/cisco-webex-teams.mdx
  docs/docs/connectors/custom-connectors.mdx
  docs/docs/connectors/facebook-messenger.mdx
  docs/docs/connectors/hangouts.mdx
  docs/docs/connectors/mattermost.mdx
  docs/docs/connectors/microsoft-bot-framework.mdx
  docs/docs/connectors/rocketchat.mdx
  docs/docs/connectors/slack.mdx
  docs/docs/connectors/telegram.mdx
  docs/docs/connectors/twilio.mdx
  docs/docs/connectors/your-own-website.mdx
  docs/docs/default-actions.mdx
  docs/docs/docker/building-in-docker.mdx
  docs/docs/docker/deploying-in-docker-compose.mdx
  docs/docs/domain.mdx
  docs/docs/event-brokers.mdx
  docs/docs/forms.mdx
  docs/docs/generating-nlu-data.mdx
  docs/docs/http-api.mdx
  docs/docs/knowledge-bases.mdx
  docs/docs/lock-stores.mdx
  docs/docs/messaging-and-voice-channels.mdx
  docs/docs/migration-guide.mdx
  docs/docs/model-configuration.mdx
  docs/docs/model-storage.mdx
  docs/docs/nlg.mdx
  docs/docs/policies.mdx
  docs/docs/prototype-an-assistant.mdx
  docs/docs/reminders-and-external-events.mdx
  docs/docs/responses.mdx
  docs/docs/retrieval-actions.mdx
  docs/docs/rules.mdx
  docs/docs/stories.mdx
  docs/docs/testing-your-assistant.mdx
  docs/docs/tracker-stores.mdx
  docs/docs/training-data-format.mdx
  docs/docs/training-data-importers.mdx
  docs/docs/tuning-your-model.mdx
  docs/plugins/included_source.js
  docs/src/theme/prism-include-languages.js
  tests/conftest.py
  tests/docs/__init__.py
  tests/docs/test_docs_training_data.py
Labels: status:ready-to-merge

#6458 improve the suggested pipeline
  data/test_config/config_empty_en.yml
  data/test_config/config_empty_en_after_dumping.yml
  data/test_config/config_empty_en_after_dumping_windows.yml
  data/test_config/config_empty_fr.yml
  data/test_config/config_empty_fr_after_dumping.yml
  poetry.lock
  pyproject.toml
  rasa/importers/autoconfig.py
  rasa/importers/default_config_en.yml
  rasa/importers/default_config_other_language.yml
  tests/importers/test_autoconfig.py
  tests/test_dependencies.py
Labels: status:ready-to-merge

#6469 merge 1.10.11 masteer
  CHANGELOG.mdx
  changelog/6044.improvement.md
  changelog/6160.bugfix.md
  changelog/6191.bugfix.md
  changelog/6226.improvement.md
  changelog/6280.bugfix.md
  changelog/6340.bugfix.rst
  rasa/core/domain.py
  tests/core/test_domain.py
  tests/nlu/extractors/test_extractor.py
Labels: status:ready-to-merge

#6478 2.0 training data format improvement
  rasa/validator.py
  tests/core/training/story_reader/test_yaml_story_reader.py
  tests/nlu/training_data/formats/test_rasa_yaml.py
  tests/test_validator.py
Labels: status:ready-to-merge

#6453 Cleanup deprecation warnings
  changelog/6453.removal.md
  data/test_domains/default_deprecated_templates.yml
  data/test_domains/default_unfeaturized_entities.yml
  data/test_domains/empty_response_format.yml
  data/test_domains/wrong_custom_response_format.yml
  data/test_domains/wrong_response_format.yml
  docs/docs/policies.mdx
  pyproject.toml
  rasa/constants.py
  rasa/core/brokers/pika.py
  rasa/core/channels/mattermost.py
  rasa/core/domain.py
  rasa/core/policies/fallback.py
  rasa/core/policies/form_policy.py
  rasa/core/policies/mapping_policy.py
  rasa/core/schemas/domain.yml
  rasa/core/tracker_store.py
  rasa/nlu/components.py
  rasa/nlu/schemas/nlu.yml
  rasa/nlu/training_data/formats/markdown.py
  rasa/nlu/training_data/formats/rasa_yaml.py
  rasa/nlu/training_data/loading.py
  rasa/server.py
  rasa/utils/common.py
  rasa/utils/pykwalify_extensions.py
  rasa/utils/schemas.yml
  rasa/utils/train_utils.py
  rasa/utils/validation.py
  tests/core/actions/test_two_stage_fallback.py
  tests/core/test_broker.py
  tests/core/test_domain.py
  tests/core/test_tracker_stores.py
  tests/nlu/training_data/formats/test_rasa_yaml.py
  tests/test_validator.py
  tests/utils/test_common.py
  tests/utils/test_validation.py
Labels: status:ready-to-merge

#6466 Train Response Selector on labels by default instead of text
  changelog/6466.improvement.md
  docs/docs/migration-guide.mdx
  examples/responseselectorbot/README.md
  examples/responseselectorbot/config.yml
  examples/responseselectorbot/data/nlu.yml
  examples/responseselectorbot/data/responses.yml
  examples/responseselectorbot/data/rules.yml
  examples/responseselectorbot/data/stories.yml
  examples/responseselectorbot/domain.yml
  rasa/core/actions/action.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/classifiers/fallback_classifier.py
  rasa/nlu/constants.py
  rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/test.py
  rasa/nlu/tokenizers/tokenizer.py
  rasa/nlu/training_data/message.py
  rasa/nlu/training_data/training_data.py
  rasa/utils/tensorflow/constants.py
  tests/core/test_actions.py
  tests/nlu/classifiers/test_fallback_classifier.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_evaluation.py
  tests/nlu/tokenizers/test_tokenizer.py
  tests/nlu/training_data/test_training_data.py
Labels: runner:gpu, status:model-regression-tests

#6485 only suggest config that is required when doing 'rasa train nlu/core'
  data/test_config/config_empty_en_after_dumping_core.yml
  data/test_config/config_empty_en_after_dumping_nlu.yml
  data/test_config/config_empty_en_after_dumping_windows_core.yml
  data/test_config/config_empty_en_after_dumping_windows_nlu.yml
  docs/docs/model-configuration.mdx
  rasa/constants.py
  rasa/importers/autoconfig.py
  rasa/importers/importer.py
  rasa/importers/rasa.py
  tests/examples/test_example_bots_training_data.py
  tests/importers/test_autoconfig.py
  tests/test_train.py
Labels: status:ready-to-merge

#6504 `rasa data convert` should be able to convert forms to `YAML` format
  rasa/cli/data.py
  rasa/core/training/story_writer/yaml_story_writer.py
  rasa/utils/io.py
  tests/cli/test_rasa_data.py
  tests/core/training/story_writer/test_yaml_story_writer.py
Labels: status:ready-to-merge

#6514 exclude rules from testing
  docs/docs/forms.mdx
  docs/docs/migration-guide.mdx
  rasa/core/test.py
  rasa/core/training/generator.py
  tests/test_test.py
Labels: status:ready-to-merge

#6512 Changes to response selector documentation
  docs/docs/components/selectors.mdx
  docs/docs/migration-guide.mdx
  docs/docs/retrieval-actions.mdx
Labels: status:ready-to-merge
