Repository RasaHQ/rasa, pull requests merged in 2020-05, with the labels that each got.

#5726 added extra info in `rasa --version` command
  changelog/5637.enhancement.rst
  rasa/__main__.py
  tests/cli/test_cli.py
Labels: area:rasa-oss :ferris_wheel:

#5829 add merge pal configuration to automatically merge ready PRs
  .github/workflows/automatic-pr-merger.yml
  .github/workflows/continous-integration.yml
  .mergepal.yml
Labels: status:ready-to-merge

#5844 Minor docs fix for Action Selection
  docs/core/policies.rst
Labels: status:ready-to-merge

#5086 add `--num-threads` argument to train cli
  changelog/5086.feature.rst
  rasa/cli/arguments/train.py
  rasa/cli/train.py
  rasa/train.py
  tests/cli/test_rasa_train.py
Labels: status:ready-to-merge

#5719 Update cloud-storage.rst
  docs/user-guide/cloud-storage.rst
Labels: status:ready-to-merge

#5743 support for additional training metadata
  changelog/5743.enhancement.rst
  rasa/nlu/training_data/formats/rasa.py
  rasa/nlu/training_data/message.py
  tests/core/test_tracker_stores.py
  tests/nlu/test_config.py
  tests/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge

#5811 event brokers documentation should say 'url' instead of 'host'
  changelog/5811.docs.rst
  docs/api/event-brokers.rst
Labels: status:ready-to-merge

#5816 Fix Redis Lock Store default db value in docs
  docs/api/lock-stores.rst
Labels: area:rasa-oss :ferris_wheel:, status:ready-to-merge, type:docs :book:

#5823 Merge 1.10.x into master
  CHANGELOG.rst
  changelog/5617.bugfix.rst
  changelog/5638.bugfix.rst
  changelog/5755.bugfix.rst
  changelog/5788.misc.rst
  changelog/5792.bugfix.rst
  changelog/5794.improvement.rst
  docs/core/forms.rst
  docs/migration-guide.rst
  docs/nlu/entity-extraction.rst
  docs/nlu/training-data-format.rst
  docs/user-guide/setting-up-ci-cd.rst
  rasa/core/domain.py
  rasa/nlu/extractors/duckling_http_extractor.py
  rasa/nlu/extractors/extractor.py
  rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
  rasa/nlu/training_data/formats/markdown.py
  rasa/utils/endpoints.py
  rasa/utils/tensorflow/models.py
  tests/core/test_domain.py
  tests/nlu/extractors/test_extractor.py
  tests/nlu/featurizers/test_spacy_featurizer.py
  tests/utils/test_endpoints.py
Labels: status:ready-to-merge

#5824 Standardize testing output: Response Selection
  changelog/5748.improvement.rst
  rasa/cli/arguments/test.py
  rasa/core/test.py
  rasa/nlu/test.py
  rasa/test.py
  rasa/utils/plotting.py
  tests/cli/test_rasa_test.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#5843 Fix shell skips button messages
  changelog/5135.bugfix.rst
  rasa/core/channels/console.py
  tests/core/channels/test_cmdline.py
Labels: status:ready-to-merge

#5848 migrate all events with rasa export
  changelog/5758.bugfix.rst
  rasa/core/exporter.py
  rasa/core/tracker_store.py
  tests/core/test_exporter.py
  tests/core/test_tracker_stores.py
Labels: status:ready-to-merge

#5687 add linkcheck CI for docs
  .github/workflows/continous-integration.yml
  CHANGELOG.rst
  docs/api/tensorflow_usage.rst
  docs/conf.py
  docs/core/knowledge-bases.rst
  docs/core/policies.rst
  docs/core/reminders-and-external-events.rst
  docs/core/responses.rst
  docs/dialogue-elements/completing-tasks.rst
  docs/index.rst
  docs/migration-guide.rst
  docs/nlu/components.rst
  docs/nlu/entity-extraction.rst
  docs/nlu/language-support.rst
  docs/user-guide/building-assistants.rst
  docs/user-guide/connectors/cisco-webex-teams.rst
  docs/user-guide/connectors/slack.rst
  docs/user-guide/connectors/your-own-website.rst
  docs/user-guide/docker/building-in-docker.rst
  docs/user-guide/setting-up-ci-cd.rst
Labels: status:ready-to-merge

#5847 Standardising testing output: Entities
  changelog/5748.improvement.rst
  rasa/nlu/test.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#5879 Fix flake8
  rasa/cli/arguments/test.py
  rasa/cli/export.py
  rasa/cli/scaffold.py
  rasa/core/exporter.py
  rasa/core/policies/embedding_policy.py
  rasa/core/training/story_conflict.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py
  rasa/nlu/test.py
  rasa/nlu/training_data/formats/markdown.py
  rasa/nlu/training_data/training_data.py
  rasa/nlu/utils/__init__.py
  tests/conftest.py
  tests/core/test_lock_store.py
  tests/nlu/tokenizers/test_lm_tokenizer.py
Labels: status:ready-to-merge

#5868 Fix newlines in response
  changelog/5521.bugfix.rst
  rasa/nlu/training_data/formats/markdown_nlg.py
  tests/nlu/training_data/test_markdown_nlg.py
Labels: status:ready-to-merge

#5886 Fixed typo contextual & users
  README.md
Labels: status:ready-to-merge

#5861 Updated stack level for FutureWarnings
  changelog/5385.bugfix.rst
  rasa/utils/common.py
  tests/utils/test_common.py
Labels: status:ready-to-merge

#5887 Fix code line in actions.py for spreadsheet info
  docs/user-guide/building-assistants.rst
Labels: status:ready-to-merge

#5859 Updated typo in commentary in socketio on credentials.yml. Also, upda…
  examples/reminderbot/credentials.yml
  rasa/cli/initial_project/credentials.yml
Labels: status:ready-to-merge

#5900 Start a server with your NLU model with "rasa run"
  docs/migrate-from/google-dialogflow-to-rasa.rst
Labels: status:ready-to-merge

#5856 merge 1.10.x to master
  CHANGELOG.rst
  changelog/5521.bugfix.rst
  changelog/5758.bugfix.rst
  docs/conf.py
  docs/core/old-core-migration-guide.rst
  docs/dialogue-elements/guiding-users.rst
  docs/nlu/choosing-a-pipeline.rst
  docs/nlu/components.rst
  docs/user-guide/building-assistants.rst
  docs/user-guide/docker/building-in-docker.rst
  docs/user-guide/how-to-deploy.rst
  docs/user-guide/rasa-tutorial.rst
  poetry.lock
  pyproject.toml
  rasa/cli/export.py
  rasa/cli/scaffold.py
  rasa/core/exporter.py
  rasa/core/tracker_store.py
  rasa/core/training/story_conflict.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py
  rasa/nlu/test.py
  rasa/nlu/training_data/formats/markdown.py
  rasa/nlu/training_data/formats/markdown_nlg.py
  rasa/nlu/training_data/training_data.py
  rasa/nlu/utils/__init__.py
  rasa/nlu/utils/bilou_utils.py
  scripts/release.py
  tests/conftest.py
  tests/core/test_exporter.py
  tests/core/test_lock_store.py
  tests/core/test_tracker_stores.py
  tests/nlu/training_data/test_markdown_nlg.py
  tests/nlu/utils/test_bilou_utils.py
Labels: status:ready-to-merge

#5888 Update retrieval-actions.rst
  docs/core/retrieval-actions.rst
Labels: status:ready-to-merge

#5693 update facebook docs with supported attachments
  changelog/5640.doc.rst
  docs/user-guide/connectors/facebook-messenger.rst
Labels: status:ready-to-merge
