Repository RasaHQ/rasa, pull requests merged in 2021-03, with the labels that each got.

#8081 Fix sanic docs link
  docs/docs/connectors/custom-connectors.mdx
  docs/docs/http-api.mdx
  docs/docs/migration-guide.mdx
Labels: status:ready-to-merge

#7860 Mark tests that train a model.
  .github/workflows/continous-integration.yml
  Makefile
  README.md
  pytest.ini
  rasa/nlu/train.py
  tests/cli/test_rasa_test.py
  tests/cli/test_rasa_train.py
  tests/conftest.py
  tests/core/actions/test_forms.py
  tests/core/actions/test_two_stage_fallback.py
  tests/core/featurizers/test_single_state_featurizers.py
  tests/core/policies/test_ted_policy.py
  tests/core/test_agent.py
  tests/core/test_evaluation.py
  tests/core/test_examples.py
  tests/core/test_lock_store.py
  tests/core/test_nlg.py
  tests/core/test_processor.py
  tests/core/test_restore.py
  tests/core/test_run.py
  tests/core/test_training.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/extractors/test_crf_entity_extractor.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_components.py
  tests/nlu/test_evaluation.py
  tests/nlu/test_interpreter.py
  tests/nlu/test_persistor.py
  tests/nlu/test_train.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_writer/test_markdown_story_writer.py
  tests/shared/importers/test_multi_project.py
  tests/test_model.py
  tests/test_server.py
  tests/test_telemetry.py
  tests/test_test.py
  tests/test_train.py
Labels: status:ready-to-merge

#7968 YAML speed up
  changelog/7952.improvement.md
  changelog/7953.improvement.md
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/utils/io.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/utils/test_io.py
Labels: status:ready-to-merge

#8085 Change policy test class fixtures to use class scope
  tests/core/test_policies.py
Labels: status:ready-to-merge

#8041 Consistent and faster stories fingerprinting
  changelog/4612.bugfix.md
  changelog/7955.improvement.md
  data/test_yaml_stories/story_with_two_equal_or_statements.yml
  rasa/shared/core/training_data/loading.py
  rasa/shared/core/training_data/story_reader/story_step_builder.py
  rasa/shared/core/training_data/structures.py
  tests/shared/core/training_data/test_graph.py
Labels: status:ready-to-merge

#7978 consistently reading and writing multiline intent examples
  data/test_multiline_intent_examples_yaml/nlu.yml
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/formats/readerwriter.py
  rasa/shared/nlu/training_data/util.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
  tests/shared/nlu/training_data/test_util.py
Labels: status:ready-to-merge

#8098 Update the fingerprinting function to recognize changes in lookup files
  changelog/7662.bugfix.md
  rasa/shared/nlu/training_data/training_data.py
  tests/shared/nlu/training_data/test_training_data.py
Labels: status:ready-to-merge

#8140 Fix a bug with `read_yaml` function failing when trying to expand an environment variable which contains a `$`
  changelog/7932.bugfix.md
  rasa/shared/utils/io.py
  tests/shared/utils/test_io.py
Labels: status:ready-to-merge

#8105 improve Lockstore queuing log message
  changelog/8100.improvement.md
  rasa/core/lock_store.py
  tests/core/test_lock_store.py
Labels: status:ready-to-merge

#7438 Implement train_step instead of overwriting fit
  changelog/7438.improvement.md
  docs/docs/components.mdx
  docs/docs/migration-guide.mdx
  docs/docs/policies.mdx
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/selectors/response_selector.py
  rasa/utils/tensorflow/callback.py
  rasa/utils/tensorflow/data_generator.py
  rasa/utils/tensorflow/model_data.py
  rasa/utils/tensorflow/models.py
  rasa/utils/tensorflow/numpy.py
  rasa/utils/tensorflow/temp_keras_modules.py
  rasa/utils/train_utils.py
  tests/core/policies/test_ted_policy.py
  tests/core/test_restore.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/utils/tensorflow/conftest.py
  tests/utils/tensorflow/test_data_generator.py
  tests/utils/tensorflow/test_model_data.py
  tests/utils/tensorflow/test_numpy.py
Labels: tools:clear-poetry-cache-unit-tests

#6964 Rename `templates` to `responses` in Rasa Open Source
  changelog/6484.misc.md
  changelog/6484.removal.md
  data/test_domains/duplicate_responses.yml
  docs/docs/components.mdx
  docs/docs/connectors/facebook-messenger.mdx
  docs/docs/migration-guide.mdx
  docs/docs/nlg.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/telemetry/events.json
  examples/nlg_server/nlg_server.py
  rasa/cli/utils.py
  rasa/core/actions/action.py
  rasa/core/actions/forms.py
  rasa/core/agent.py
  rasa/core/nlg/__init__.py
  rasa/core/nlg/callback.py
  rasa/core/nlg/generator.py
  rasa/core/nlg/interpolator.py
  rasa/core/nlg/response.py
  rasa/core/nlg/template.py
  rasa/core/policies/policy.py
  rasa/core/training/converters/responses_prefix_converter.py
  rasa/core/training/interactive.py
  rasa/model.py
  rasa/nlu/constants.py
  rasa/nlu/selectors/response_selector.py
  rasa/shared/core/domain.py
  rasa/shared/importers/importer.py
  rasa/telemetry.py
  rasa/train.py
  rasa/validator.py
  tests/core/actions/test_forms.py
  tests/core/actions/test_loops.py
  tests/core/actions/test_two_stage_fallback.py
  tests/core/conftest.py
  tests/core/featurizers/test_single_state_featurizers.py
  tests/core/policies/test_rule_policy.py
  tests/core/test_actions.py
  tests/core/test_examples.py
  tests/core/test_nlg.py
  tests/core/test_processor.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_train.py
  tests/shared/core/test_domain.py
  tests/shared/importers/test_importer.py
  tests/shared/importers/test_rasa.py
  tests/test_train.py
  tests/test_validator.py
Labels: area:rasa-oss :ferris_wheel:, priority:low, type:maintenance :wrench:

#8161 Rules states should not include the initial values of slots.
  changelog/7450.bugfix.md
  rasa/core/featurizers/tracker_featurizers.py
  rasa/core/policies/rule_policy.py
  rasa/shared/core/domain.py
  rasa/shared/core/generator.py
  rasa/shared/core/slots.py
  rasa/shared/core/trackers.py
  tests/core/policies/test_rule_policy.py
  tests/shared/core/test_slots.py
Labels: tools:clear-poetry-cache-unit-tests, unit-tests:clear-poetry-cache

#8197 Added a timeout on a test's mongodb connection
  tests/core/test_tracker_stores.py
Labels: type:maintenance :wrench:

#8193 Unify test file constants and fixtures
  tests/cli/test_rasa_data.py
  tests/cli/test_rasa_interactive.py
  tests/conftest.py
  tests/core/actions/test_forms.py
  tests/core/conftest.py
  tests/core/featurizers/test_tracker_featurizer.py
  tests/core/policies/test_ted_policy.py
  tests/core/test_actions.py
  tests/core/test_agent.py
  tests/core/test_broker.py
  tests/core/test_ensemble.py
  tests/core/test_evaluation.py
  tests/core/test_nlg.py
  tests/core/test_policies.py
  tests/core/test_tracker_stores.py
  tests/core/test_training.py
  tests/core/training/test_interactive.py
  tests/core/training/test_story_conflict.py
  tests/core/utilities.py
  tests/integration_tests/core/conftest.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/classifiers/test_keyword_classifier.py
  tests/nlu/conftest.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_components.py
  tests/nlu/test_evaluation.py
  tests/nlu/test_train.py
  tests/shared/core/test_dialogues.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/story_reader/test_common_story_reader.py
  tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
  tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
  tests/shared/core/training_data/story_writer/test_yaml_story_writer.py
  tests/shared/core/training_data/test_structures.py
  tests/shared/core/training_data/test_visualization.py
  tests/shared/test_data.py
  tests/test_model.py
  tests/test_model_training.py
  tests/test_server.py
  tests/test_telemetry.py
  tests/test_validator.py
  tests/utils/test_endpoints.py
Labels: tools:clear-poetry-cache-unit-tests, unit-tests:clear-poetry-cache

#8204 8116 replace moodbot example fixtures
  data/test_moodbot/config.yml
  data/test_moodbot/credentials.yml
  data/test_moodbot/data/nlu.yml
  data/test_moodbot/data/rules.yml
  data/test_moodbot/data/stories.yml
  data/test_moodbot/domain.yml
  data/test_spacybot/config.yml
  data/test_spacybot/data/nlu.yml
  data/test_spacybot/data/stories.yml
  data/test_spacybot/domain.yml
  tests/cli/test_rasa_data.py
  tests/cli/test_rasa_interactive.py
  tests/conftest.py
  tests/core/featurizers/test_single_state_featurizers.py
  tests/core/test_agent.py
  tests/core/test_examples.py
  tests/core/test_run.py
  tests/examples/test_example_bots_training_data.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/shared/core/test_domain.py
  tests/shared/core/test_trackers.py
  tests/shared/core/training_data/test_structures.py
  tests/shared/utils/test_validation.py
  tests/test_model_training.py
  tests/test_validator.py
Labels: tools:clear-poetry-cache-unit-tests, unit-tests:clear-poetry-cache

#8254 Fix test_server.py:test_pushing_event occasionally failing
  tests/test_server.py
Labels: type:maintenance :wrench:

#7869 spaCy 3.0
  Makefile
  changelog/7869.feature.md
  data/test_config/config_pretrained_embeddings_spacy_de.yml
  data/test_config/config_spacy_entity_extractor.yml
  docker/Dockerfile.pretrained_embeddings_spacy_de
  docker/Dockerfile.pretrained_embeddings_spacy_en
  docker/configs/config_pretrained_embeddings_spacy_de.yml
  docker/configs/config_pretrained_embeddings_spacy_en.yml
  docker/configs/config_pretrained_embeddings_spacy_en_duckling.yml
  docs/docs/components.mdx
  docs/docs/installation.mdx
  docs/docs/migration-guide.mdx
  docs/docs/reaching-out-to-user.mdx
  docs/docs/tuning-your-model.mdx
  examples/moodbot/config.yml
  examples/reminderbot/config.yml
  poetry.lock
  pyproject.toml
  rasa/nlu/utils/spacy_utils.py
  tests/conftest.py
  tests/nlu/conftest.py
  tests/nlu/extractors/test_crf_entity_extractor.py
  tests/nlu/test_evaluation.py
  tests/nlu/test_spacy_utils.py
  tests/nlu/test_train.py
  tests/nlu/tokenizers/test_spacy_tokenizer.py
Labels: area:rasa-oss :ferris_wheel:, area:rasa-oss/ml/nlu-components

#8222 Raising exception when having empty intent or entity mapping in the domain
  changelog/7916.bugfix.md
  rasa/shared/constants.py
  rasa/shared/core/domain.py
  tests/shared/core/test_domain.py
Labels: area:rasa-oss :ferris_wheel:

#8321 included the enable-api command in step 5
  docs/docs/migrate-from/google-dialogflow-to-rasa.mdx
Labels: type:docs :book:

#8259 Changes in the release section of the readme
  README.md
Labels: area:rasa-oss :ferris_wheel:

#8329 Fix model regression tests after Spacy has been updated
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
Labels: type:maintenance :wrench:
