Repository RasaHQ/rasa, pull requests merged in 2021-02, with the labels that each got.

#7785 add bilou tagging to e2e ted entities
  changelog/7579.improvement.md
  docs/docs/components.mdx
  docs/docs/policies.mdx
  rasa/core/featurizers/single_state_featurizer.py
  rasa/core/featurizers/tracker_featurizers.py
  rasa/core/policies/policy.py
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/extractors/extractor.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/utils/bilou_utils.py
  rasa/utils/tensorflow/model_data_utils.py
  rasa/utils/train_utils.py
  tests/core/featurizers/test_single_state_featurizers.py
  tests/utils/tensorflow/test_model_data_utils.py
Labels: tools:clear-poetry-cache-unit-tests

#7857 Fix typo
  rasa/core/policies/ted_policy.py
Labels: status:ready-to-merge

#7822 Create a separate Docker base image for a build step
  .github/workflows/continous-integration.yml
  Dockerfile
  Makefile
  docker/Dockerfile.base
  docker/Dockerfile.base-builder
  docker/Dockerfile.base-poetry
  docker/Dockerfile.full
  docker/Dockerfile.pretrained_embeddings_mitie_en
  docker/Dockerfile.pretrained_embeddings_spacy_de
  docker/Dockerfile.pretrained_embeddings_spacy_en
  docker/docker-bake.hcl
Labels: area:rasa-oss/infrastructure :bullettrain_front:

#7859 Merge 2.2.x main
  docs/_redirects
  docs/robots.txt
Labels: status:ready-to-merge

#7861 add missing 'confused with' field to model report
  changelog/7861.bugfix.md
  rasa/nlu/test.py
  rasa/server.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#7872 prepared release of version 2.2.9
  CHANGELOG.mdx
  changelog/7861.bugfix.md
  pyproject.toml
  rasa/version.py
  tests/core/test_evaluation.py
  tests/core/test_examples.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#7871 temporary fix of persisting entity tags
  rasa/core/featurizers/tracker_featurizers.py
Labels: status:ready-to-merge, type:bug :bug:

#7847 Clean Duplicate Line
  rasa/shared/nlu/training_data/formats/__init__.py
Labels: status:ready-to-merge

#7864 sanic worker doc update
  docs/docs/http-api.mdx
Labels: type:docs :book:

#7884 Rename _redirects to _headers and update X-Robots-Tag
  docs/_headers
  docs/conf.py
Labels: status:ready-to-merge

#7754 Backport of aio-pika implementation to 1.10.X
  poetry.lock
  pyproject.toml
  rasa/cli/export.py
  rasa/core/brokers/broker.py
  rasa/core/brokers/file.py
  rasa/core/brokers/kafka.py
  rasa/core/brokers/pika.py
  rasa/core/brokers/sql.py
  rasa/core/exporter.py
  rasa/core/lock_store.py
  rasa/core/run.py
  rasa/core/tracker_store.py
  rasa/nlu/extractors/spacy_entity_extractor.py
  rasa/nlu/tokenizers/spacy_tokenizer.py
  rasa/nlu/utils/spacy_utils.py
  rasa/run.py
  rasa/server.py
  rasa/utils/common.py
  tests/cli/test_rasa_export.py
  tests/core/test_broker.py
  tests/core/test_exporter.py
Labels: status:ready-to-merge

#7867 invert dialogue time in ted
  changelog/7867.bugfix.md
  changelog/7867.improvement.md
  docs/docs/policies.mdx
  rasa/core/policies/ted_policy.py
  rasa/utils/tensorflow/models.py
Labels: status:ready-to-merge

#7890 Prepare release 1.10.22
  CHANGELOG.rst
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7877 Update UnsupportedModelError
  changelog/7069.improvement.md
  rasa/nlu/model.py
Labels: status:ready-to-merge

#7907 prepared release of version 2.2.10
  CHANGELOG.mdx
  changelog/7069.improvement.md
  changelog/7885.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7616 Add sigmoid to softmax loss
  changelog/7616.improvement.md
  data/test_config/config_empty_en_after_dumping.yml
  data/test_config/config_empty_en_after_dumping_core.yml
  data/test_config/config_empty_en_after_dumping_nlu.yml
  data/test_config/config_empty_fr_after_dumping.yml
  data/test_config/config_with_comments_after_dumping.yml
  docs/docs/components.mdx
  docs/docs/migration-guide.mdx
  docs/docs/policies.mdx
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/selectors/response_selector.py
  rasa/nlu/test.py
  rasa/shared/importers/default_config.yml
  rasa/utils/plotting.py
  rasa/utils/tensorflow/constants.py
  rasa/utils/tensorflow/exceptions.py
  rasa/utils/tensorflow/layers.py
  rasa/utils/tensorflow/models.py
  rasa/utils/train_utils.py
  tests/core/policies/test_ted_policy.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/selectors/test_selectors.py
  tests/utils/test_train_utils.py
Labels: status:ready-to-merge

#7915 Merge 2.2.10 main
  CHANGELOG.mdx
  docs/docs/http-api.mdx
  poetry.lock
  pyproject.toml
  rasa/nlu/model.py
  rasa/nlu/test.py
  rasa/server.py
  rasa/version.py
  tests/core/test_evaluation.py
  tests/core/test_examples.py
  tests/nlu/test_evaluation.py
Labels: status:ready-to-merge

#7886 ignore missing docstrings for magic methods
  setup.cfg
Labels: status:ready-to-merge

#7923 fix typo where wrong form of send is used
  docs/docs/nlg.mdx
Labels: status:ready-to-merge

#7922 make metadata accessible for custom action_session_start
  changelog/7420.bugfix.md
  changelog/7420.improvement.md
  changelog/7420.misc.md
  data/test_trackers/tracker_moodbot.json
  docs/docs/default-actions.mdx
  rasa/core/processor.py
  rasa/shared/core/constants.py
  rasa/shared/core/domain.py
  rasa/shared/core/slots.py
  rasa/shared/core/trackers.py
  tests/core/test_actions.py
  tests/core/test_processor.py
  tests/shared/core/test_slots.py
  tests/shared/importers/test_rasa.py
  tests/test_server.py
Labels: status:ready-to-merge

#7647 custom channel connector docs improvements
  docs/docs/connectors/custom-connectors.mdx
Labels: status:ready-to-merge

#7937 merge 2.2.x main
  .github/workflows/documentation.yml
  Makefile
  scripts/push_docs_to_branch.sh
Labels: status:ready-to-merge

#7938 Make `similarity_confidence_from_embeddings` public
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/selectors/response_selector.py
  rasa/utils/tensorflow/layers.py
Labels: status:ready-to-merge

#7939 Prepare release 2.3.0
  CHANGELOG.mdx
  changelog/5673.improvement.md
  changelog/5986.improvement.md
  changelog/7292.improvement.md
  changelog/7303.improvement.md
  changelog/7420.bugfix.md
  changelog/7420.improvement.md
  changelog/7420.misc.md
  changelog/7515.misc.rst
  changelog/7574.misc.md
  changelog/7579.improvement.md
  changelog/7601.misc.md
  changelog/7616.improvement.md
  changelog/7707.bugfix.md
  changelog/7710.bugfix.md
  changelog/7749.bugfix.md
  changelog/7751.bugfix.md
  changelog/7817.improvement.md
  changelog/7829.bugfix.md
  changelog/7848.improvement.md
  changelog/7867.bugfix.md
  changelog/7867.improvement.md
  poetry.lock
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7933 Rasa NLU data spec update
  changelog/7063.bugfix.md
  docs/static/spec/rasa.yml
  rasa/server.py
  tests/test_server.py
Labels: status:ready-to-merge

#7961 script to update path of sources loaded with remark-source to a versioned path
  docs/package.json
  docs/plugins/included_source.js
  docs/scripts/update_versioned_sources.js
  scripts/push_docs_to_branch.sh
Labels: status:ready-to-merge

#7981 prepared release of version 2.3.1
  CHANGELOG.mdx
  changelog/7970.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7982 [2.3.x] Fix tagging the latest stable version as latest
  .github/workflows/continous-integration.yml
Labels: status:ready-to-merge

#7983 Fix tagging the latest stable version as latest
  .github/workflows/continous-integration.yml
Labels: status:ready-to-merge

#7949 Avoid validating slot of previous form
  changelog/7949.bugfix.md
  rasa/core/actions/forms.py
  tests/core/actions/test_forms.py
Labels: status:ready-to-merge

#7967 fix typo in test
  tests/test_server.py
Labels: status:ready-to-merge

#7965 validate model config
  changelog/7893.improvement.md
  rasa/cli/data.py
  rasa/cli/default_config.yml
  rasa/core/config.py
  rasa/nlu/config.py
  rasa/shared/constants.py
  rasa/shared/core/training_data/story_reader/yaml_story_reader.py
  rasa/shared/importers/multi_project.py
  rasa/shared/nlu/training_data/schemas/config.yml
  rasa/shared/nlu/training_data/schemas/nlu.yml
  rasa/shared/utils/io.py
  rasa/shared/utils/schemas/config.yml
  rasa/shared/utils/schemas/domain.yml
  rasa/shared/utils/schemas/model_config.yml
  rasa/shared/utils/schemas/stories.yml
  tests/cli/test_rasa_train.py
  tests/conftest.py
  tests/shared/utils/test_io.py
  tests/shared/utils/test_validation.py
Labels: status:ready-to-merge

#8015 Merge 2.3.x into main
  CHANGELOG.mdx
  pyproject.toml
  rasa/shared/utils/validation.py
  rasa/version.py
  tests/shared/utils/test_validation.py
Labels: status:ready-to-merge

#7800 Integration tests workflow for Postgres, Redis, RabbitMQ
  .github/workflows/continous-integration.yml
  Makefile
  README.md
  changelog/7680.improvement.md
  pytest.ini
  rasa/core/tracker_store.py
  tests/integration_tests/__init__.py
  tests/integration_tests/core/__init__.py
  tests/integration_tests/core/brokers/__init__.py
  tests/integration_tests/core/brokers/conftest.py
  tests/integration_tests/core/brokers/test_pika.py
  tests/integration_tests/core/conftest.py
  tests/integration_tests/core/test_lock_store.py
  tests/integration_tests/core/test_tracker_store.py
  tests_deployment/.env.example
  tests_deployment/docker-compose.integration.yml
Labels: status:ready-to-merge

#8053 Merge 2.3.x
  CHANGELOG.mdx
  pyproject.toml
  rasa/core/agent.py
  rasa/core/processor.py
  rasa/version.py
  tests/core/actions/test_forms.py
  tests/core/conftest.py
  tests/core/test_processor.py
  tests/test_server.py
Labels: status:ready-to-merge

#8014 Add warnings for wrong values of model_confidence parameter
  .github/runner/github-runner-deployment.yaml.tmpl
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  CHANGELOG.mdx
  changelog/8014.bugfix.md
  data/test_config/config_empty_en_after_dumping.yml
  data/test_config/config_empty_en_after_dumping_core.yml
  data/test_config/config_empty_en_after_dumping_nlu.yml
  data/test_config/config_empty_fr_after_dumping.yml
  data/test_config/config_with_comments_after_dumping.yml
  docs/docs/components.mdx
  docs/docs/migration-guide.mdx
  docs/docs/policies.mdx
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/selectors/response_selector.py
  rasa/shared/importers/default_config.yml
  rasa/utils/tensorflow/constants.py
  rasa/utils/tensorflow/layers.py
  rasa/utils/train_utils.py
  tests/core/policies/test_ted_policy.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/selectors/test_selectors.py
  tests/utils/test_train_utils.py
Labels: runner:gpu
