Repository RasaHQ/rasa, pull requests merged in 2021-01, with the labels that each got.

#7688 Prepare release 2.2.3
  CHANGELOG.mdx
  changelog/7622.bugfix.md
  pyproject.toml
  rasa/server.py
  rasa/version.py
  tests/test_server.py
Labels: status:ready-to-merge

#7520 improve warning for missing RulePolicy
  changelog/7520.improvement.md
  rasa/core/policies/ensemble.py
  rasa/shared/constants.py
Labels: status:ready-to-merge

#7692 make cryptography dep required
  changelog/7692.bugfix.md
  poetry.lock
  pyproject.toml
Labels: status:ready-to-merge

#7638 Backport Multiple Sanic Workers fix for 1.10.x
  changelog/7638.bugfix.md
  rasa/core/utils.py
  tests/core/test_utils.py
Labels: status:ready-to-merge

#7700 use session scoped formbot agent fixture
  tests/core/conftest.py
  tests/core/test_examples.py
Labels: status:ready-to-merge

#7699 prepared release of version 2.2.4
  CHANGELOG.mdx
  changelog/7520.improvement.md
  changelog/7692.bugfix.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7702 merge 2.2.4 master
  .github/workflows/continous-integration.yml
  CHANGELOG.mdx
  docs/docs/connectors/telegram.mdx
  docs/docs/setting-up-ci-cd.mdx
  docs/docs/testing-your-assistant.mdx
  docs/static/img/train-test-github-action.png
  poetry.lock
  pyproject.toml
  rasa/cli/x.py
  rasa/core/actions/action.py
  rasa/core/actions/forms.py
  rasa/core/brokers/kafka.py
  rasa/core/channels/telegram.py
  rasa/core/policies/ensemble.py
  rasa/core/tracker_store.py
  rasa/server.py
  rasa/shared/constants.py
  rasa/shared/nlu/training_data/schemas/responses.yml
  rasa/version.py
  tests/core/actions/test_forms.py
  tests/core/conftest.py
  tests/core/test_actions.py
  tests/core/test_channels.py
  tests/core/test_examples.py
  tests/core/test_tracker_stores.py
  tests/test_server.py
Labels: status:ready-to-merge

#7611 Compare to f1-score if an accuracy field doesn't exist
  .github/templates/model_regression_test_results.tmpl
Labels: area:rasa-oss/infrastructure :bullettrain_front:, priority:normal

#7711 Prepare release 2.2.5
  CHANGELOG.mdx
  changelog/7603.bugfix.md
  poetry.lock
  pyproject.toml
  rasa/server.py
  rasa/utils/common.py
  rasa/version.py
  tests/utils/test_common.py
Labels: status:ready-to-merge

#7717 fix EventBroker async warning
  changelog/7717.bugfix.md
  rasa/core/exporter.py
  rasa/core/run.py
  tests/core/test_exporter.py
  tests/core/test_run.py
Labels: status:ready-to-merge

#7725 typofix: 'Ctr-c' -> 'Ctrl-c'
  rasa/core/training/interactive.py
Labels: status:ready-to-merge

#7292 Iterate on Sentry filtering
  changelog/7292.improvement.md
  data/test_endpoints/example_endpoints.yml
  rasa/core/brokers/broker.py
  rasa/core/tracker_store.py
  rasa/shared/exceptions.py
  rasa/shared/nlu/training_data/entities_parser.py
  rasa/shared/nlu/training_data/formats/markdown.py
  rasa/shared/utils/common.py
  rasa/shared/utils/validation.py
  rasa/telemetry.py
  rasa/utils/endpoints.py
  tests/core/test_broker.py
  tests/core/test_tracker_stores.py
  tests/shared/nlu/training_data/formats/test_markdown.py
  tests/shared/nlu/training_data/test_entities_parser.py
  tests/shared/utils/test_common.py
  tests/shared/utils/test_validation.py
  tests/utils/test_endpoints.py
Labels: status:ready-to-merge

#7750 Add a step to the CI to clear poetry cache
  .github/workflows/continous-integration.yml
Labels: area:rasa-oss/infrastructure :bullettrain_front:

#7730 Fix typo in GitHub feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: status:ready-to-merge, type:maintenance :wrench:

#7759 Change cache key for poetry by a secret variable
  .github/workflows/ci-model-regression-on-schedule.yml
  .github/workflows/ci-model-regression.yml
  .github/workflows/continous-integration.yml
  .github/workflows/documentation.yml
  .github/workflows/security-scans.yml
Labels: area:rasa-oss/infrastructure :bullettrain_front:

#7755 Fix typo
  docs/docs/stories.mdx
Labels: status:ready-to-merge, type:docs :book:

#7769 Fix incremental training when no entities are present in the training data
  changelog/7720.bugfix.md
  rasa/nlu/classifiers/diet_classifier.py
  tests/nlu/classifiers/test_diet_classifier.py
Labels: status:ready-to-merge

#7773 fix now broken link to RocketChat docs
  docs/docs/connectors/rocketchat.mdx
Labels: status:ready-to-merge

#7768 Add prepare-transformers target to Makefile
  Makefile
  data/test/hf_transformers_models.txt
Labels: status:ready-to-merge

#7767 Add resolutions in docs/package.json to fix vulnerabilities
  docs/package.json
  docs/yarn.lock
Labels: status:ready-to-merge

#7716 Add `split_entities_config` to TEDPolicy
  changelog/7707.bugfix.md
  docs/docs/policies.mdx
  rasa/core/policies/ted_policy.py
  rasa/nlu/extractors/extractor.py
  rasa/utils/train_utils.py
  tests/utils/test_train_utils.py
Labels: tools:clear-poetry-cache-unit-tests

#7761 Support for writing NLU intent/example metadata to YAML
  changelog/7731.improvement.md
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/formats/readerwriter.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Labels: status:ready-to-merge

#7796 Prepare release 2.2.7
  CHANGELOG.mdx
  changelog/4311.bugfix.md
  changelog/7731.improvement.md
  pyproject.toml
  rasa/version.py
Labels: status:ready-to-merge

#7475 document connecting to an NLU only server
  docs/docs/nlu-only-server.mdx
  docs/sidebars.js
Labels: status:ready-to-merge

#5673 Attention weight logging
  changelog/5673.improvement.md
  docs/docs/tuning-your-model.mdx
  rasa/core/policies/policy.py
  rasa/core/policies/ted_policy.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/nlu/components.py
  rasa/nlu/config.py
  rasa/nlu/constants.py
  rasa/nlu/featurizers/featurizer.py
  rasa/nlu/selectors/response_selector.py
  rasa/shared/constants.py
  rasa/shared/nlu/training_data/message.py
  rasa/utils/tensorflow/models.py
  rasa/utils/tensorflow/numpy.py
  rasa/utils/tensorflow/transformer.py
  tests/conftest.py
  tests/core/conftest.py
  tests/core/policies/test_ted_policy.py
  tests/core/test_policies.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/nlu/selectors/test_selectors.py
  tests/nlu/test_config.py
  tests/shared/nlu/training_data/test_message.py
  tests/utils/tensorflow/test_numpy.py
Labels: status:ready-to-merge

#7816 Merge 2.2.7 to main
  CHANGELOG.mdx
  docs/docs/domain.mdx
  poetry.lock
  pyproject.toml
  rasa/core/exporter.py
  rasa/core/run.py
  rasa/core/training/story_conflict.py
  rasa/nlu/classifiers/diet_classifier.py
  rasa/server.py
  rasa/shared/core/domain.py
  rasa/shared/nlu/training_data/formats/rasa_yaml.py
  rasa/shared/nlu/training_data/formats/readerwriter.py
  rasa/utils/common.py
  rasa/version.py
  tests/core/test_exporter.py
  tests/core/test_run.py
  tests/nlu/classifiers/test_diet_classifier.py
  tests/shared/core/test_domain.py
  tests/shared/nlu/training_data/formats/test_rasa_yaml.py
  tests/test_validator.py
  tests/utils/test_common.py
Labels: status:ready-to-merge

#7479 updated dependencies
  poetry.lock
  pyproject.toml
Labels: tools:clear-poetry-cache-unit-tests, type:dependencies, unit-tests:clear-poetry-cache

#7821 replace short SHA to long SHA
  .github/workflows/vulnerability-scan.yml
Labels: status:ready-to-merge

#7817 use simple random
  changelog/7817.improvement.md
  rasa/utils/tensorflow/layers.py
Labels: status:ready-to-merge

#7795 Loading the data in core test with TrainingDataImporter interface
  changelog/5986.improvement.md
  rasa/core/test.py
  tests/core/test_evaluation.py
Labels: tools:clear-poetry-cache-unit-tests

#7749 fix e2e overriding loop prediction
  changelog/7749.bugfix.md
  rasa/core/policies/ensemble.py
  rasa/core/policies/policy.py
  rasa/core/policies/rule_policy.py
  tests/core/policies/test_rule_policy.py
  tests/core/test_ensemble.py
Labels: status:ready-to-merge, tools:clear-poetry-cache-unit-tests

#7502 updated build backend
  .github/poetry_version.txt
  .github/workflows/continous-integration.yml
  pyproject.toml
  scripts/poetry-version.sh
Labels: tools:clear-poetry-cache-unit-tests, unit-tests:clear-poetry-cache
